# Generated by Django 5.2.15 on 2026-06-11 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_alter_candidate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInterviewerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('interviewer_name', models.CharField(max_length=255, verbose_name='نام مصاحبه\u200cگر')),
                ('score', models.FloatField(default=0.0, verbose_name='نمره ثبت شده')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='وزن نمره')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('stage_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_interviewer_scores', to='candidates.applicationstagestate', verbose_name='وضعیت مرحله')),
            ],
            options={
                'verbose_name': 'نمره مصاحبه\u200cگر خارجی',
                'verbose_name_plural': 'نمرات مصاحبه\u200cگران خارجی',
            },
        ),
    ]
