# Generated by Django 5.2.15 on 2026-06-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_externalinterviewerscore'),
        ('jobs', '0014_alter_jobopportunity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDefaultInterviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('interviewer_name', models.CharField(max_length=255, verbose_name='نام مصاحبه\u200cگر')),
                ('weight', models.PositiveIntegerField(default=100, verbose_name='وزن نمره')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_interviewers', to='jobs.jobopportunity', verbose_name='فرصت شغلی')),
            ],
            options={
                'verbose_name': 'مصاحبه\u200cگر پیش\u200cفرض فرصت شغلی',
                'verbose_name_plural': 'مصاحبه\u200cگران پیش\u200cفرض فرصت شغلی',
                'ordering': ['job', 'interviewer_name'],
            },
        ),
    ]
