# Generated by Django 5.2.15 on 2026-06-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_jobdefaultinterviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstagestate',
            name='is_manually_edited',
            field=models.BooleanField(default=False, verbose_name='ویرایش شده به صورت دستی'),
        ),
    ]
