# Generated by Django 5.2.15 on 2026-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_applicationstagestate_is_manually_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پذیرش نهایی'),
        ),
    ]
