# Generated by Django 5.2.17 on 2026-09-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_recalculate_all_application_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstagestate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار ارزیابی'), ('COMPLETED', 'قبول شده در این مرحله'), ('FAILED', 'مردود شده در این مرحله'), ('ABSENT', 'غایب در این مرحله')], default='PENDING', max_length=20, verbose_name='وضعیت مرحله'),
        ),
        migrations.AlterField(
            model_name='interviewerscore',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار ارزیابی'), ('COMPLETED', 'قبول شده در این مرحله'), ('FAILED', 'مردود شده در این مرحله'), ('ABSENT', 'غایب در این مرحله')], default='PENDING', max_length=20, verbose_name='وضعیت مرحله'),
        ),
    ]
