# Generated by Django 5.2.17 on 2026-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_alter_applicationstagestate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('SMS', 'پیامک'), ('EMAIL', 'ایمیل'), ('BALE', 'پیام\u200cرسان بله')], max_length=10, verbose_name='نوع اعلان'),
        ),
    ]
