# Generated by Django 5.2.15 on 2026-06-03 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('role', models.CharField(choices=[('HR_MANAGER', 'مدیر ارشد منابع انسانی'), ('RECRUITER', 'کارشناس جذب و استخدام'), ('INTERVIEWER', 'ارزیاب مصاحبه'), ('ADMIN', 'مدیر سیستم')], default='INTERVIEWER', max_length=20, verbose_name='نقش')),
                ('is_external', models.BooleanField(default=False, verbose_name='ارزیاب خارجی')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
    ]
