from django.urls import path
from .views import (
    JobOpportunityListView,
    JobOpportunityCreateView,
    JobOpportunityUpdateView,
    JobOpportunityDeleteView,
    JobOpportunityDeleteConfirmView,
    WorkflowTemplateListView,
    WorkflowTemplateCreateView,
    WorkflowTemplateUpdateView,
    WorkflowTemplateDeleteView,
    ExportJobsExcelView,
    WorkflowStagesPreviewView,
    JobOpportunityPrintDocView,
    JobOpportunityPrintAdView,
    JobOpportunityBulkStatusView,
    CentralCompetencyListView,
    CentralCompetencyUploadView,
    RecruitmentPatternDashboardView,
    JobCompetencyConfigView,
    JobAssessmentPlanPrintView,
    SearchPostsApiView,
    SearchPostsDetailApiView,
    CustomCompetenciesReportView,
    SearchCompetenciesApiView,
    AISettingView,
    JobAIStrategyPrintView,
    OrganizationSettingView,
    CompetencyModelDetailApiView,
    CompetencyModelListView,
    CompetencyModelManageView,
    CompetencyModelItemManageView
)


urlpatterns = [
    path('', JobOpportunityListView.as_view(), name='job_list'),
    path('add/', JobOpportunityCreateView.as_view(), name='job_add'),
    path('<int:pk>/edit/', JobOpportunityUpdateView.as_view(), name='job_edit'),
    path('<int:pk>/delete/', JobOpportunityDeleteView.as_view(), name='job_delete'),
    path('<int:pk>/delete/confirm/', JobOpportunityDeleteConfirmView.as_view(), name='job_delete_confirm'),
    path('<int:pk>/print/', JobOpportunityPrintDocView.as_view(), name='job_print_doc'),
    path('<int:pk>/print-ad/', JobOpportunityPrintAdView.as_view(), name='job_print_ad'),
    path('export/excel/', ExportJobsExcelView.as_view(), name='job_export_excel'),
    path('bulk-status-update/', JobOpportunityBulkStatusView.as_view(), name='job_bulk_status_update'),
    
    path('workflows/', WorkflowTemplateListView.as_view(), name='workflow_list'),
    path('workflows/add/', WorkflowTemplateCreateView.as_view(), name='workflow_add'),
    path('workflows/<int:pk>/edit/', WorkflowTemplateUpdateView.as_view(), name='workflow_edit'),
    path('workflows/<int:pk>/delete/', WorkflowTemplateDeleteView.as_view(), name='workflow_delete'),
    path('workflows/<int:pk>/stages/', WorkflowStagesPreviewView.as_view(), name='workflow_stages_preview'),

    path('competencies/', CentralCompetencyListView.as_view(), name='competency_list'),
    path('competencies/upload/', CentralCompetencyUploadView.as_view(), name='competency_upload'),
    path('competencies/patterns/', RecruitmentPatternDashboardView.as_view(), name='recruitment_patterns'),
    path('competencies/custom-report/', CustomCompetenciesReportView.as_view(), name='custom_competencies_report'),
    path('competencies/models/', CompetencyModelListView.as_view(), name='competency_model_list'),
    path('competencies/models/manage/', CompetencyModelManageView.as_view(), name='competency_model_manage'),
    path('competencies/models/<int:model_id>/items/', CompetencyModelItemManageView.as_view(), name='competency_model_item_manage'),
    path('competencies/settings/ai/', AISettingView.as_view(), name='ai_setting'),
    path('settings/organization/', OrganizationSettingView.as_view(), name='organization_setting'),

    path('api/posts/search/', SearchPostsApiView.as_view(), name='search_posts_api'),
    path('api/posts/detail/', SearchPostsDetailApiView.as_view(), name='post_detail_api'),
    path('api/competencies/search/', SearchCompetenciesApiView.as_view(), name='search_competencies_api'),
    path('api/competency-models/<int:model_id>/', CompetencyModelDetailApiView.as_view(), name='competency_model_detail_api'),
    path('<int:job_id>/competencies/', JobCompetencyConfigView.as_view(), name='job_competency_config'),
    path('<int:job_id>/assessment-plan/print/', JobAssessmentPlanPrintView.as_view(), name='job_assessment_plan_print'),
    path('competencies/patterns/print-ai-strategy/', JobAIStrategyPrintView.as_view(), name='job_ai_strategy_print'),
]
