from django.urls import path
from .views import (
    JobOpportunityListView,
    JobOpportunityCreateView,
    JobOpportunityUpdateView,
    JobOpportunityDeleteView,
    JobOpportunityDeleteConfirmView,
    WorkflowTemplateListView,
    WorkflowTemplateCreateView,
    WorkflowTemplateUpdateView,
    WorkflowTemplateDeleteView,
    ExportJobsExcelView,
    WorkflowStagesPreviewView,
    JobOpportunityPrintDocView,
    JobOpportunityBulkStatusView,
    CentralCompetencyListView,
    CentralCompetencyUploadView,
    RecruitmentPatternDashboardView,
    JobCompetencyConfigView,
    JobAssessmentPlanPrintView,
    SearchPostsApiView,
    SearchPostsDetailApiView,
    CustomCompetenciesReportView
)

urlpatterns = [
    path('', JobOpportunityListView.as_view(), name='job_list'),
    path('add/', JobOpportunityCreateView.as_view(), name='job_add'),
    path('<int:pk>/edit/', JobOpportunityUpdateView.as_view(), name='job_edit'),
    path('<int:pk>/delete/', JobOpportunityDeleteView.as_view(), name='job_delete'),
    path('<int:pk>/delete/confirm/', JobOpportunityDeleteConfirmView.as_view(), name='job_delete_confirm'),
    path('<int:pk>/print/', JobOpportunityPrintDocView.as_view(), name='job_print_doc'),
    path('export/excel/', ExportJobsExcelView.as_view(), name='job_export_excel'),
    path('bulk-status-update/', JobOpportunityBulkStatusView.as_view(), name='job_bulk_status_update'),
    
    path('workflows/', WorkflowTemplateListView.as_view(), name='workflow_list'),
    path('workflows/add/', WorkflowTemplateCreateView.as_view(), name='workflow_add'),
    path('workflows/<int:pk>/edit/', WorkflowTemplateUpdateView.as_view(), name='workflow_edit'),
    path('workflows/<int:pk>/delete/', WorkflowTemplateDeleteView.as_view(), name='workflow_delete'),
    path('workflows/<int:pk>/stages/', WorkflowStagesPreviewView.as_view(), name='workflow_stages_preview'),

    path('competencies/', CentralCompetencyListView.as_view(), name='competency_list'),
    path('competencies/upload/', CentralCompetencyUploadView.as_view(), name='competency_upload'),
    path('competencies/patterns/', RecruitmentPatternDashboardView.as_view(), name='recruitment_patterns'),
    path('competencies/custom-report/', CustomCompetenciesReportView.as_view(), name='custom_competencies_report'),
    path('api/posts/search/', SearchPostsApiView.as_view(), name='search_posts_api'),
    path('api/posts/detail/', SearchPostsDetailApiView.as_view(), name='post_detail_api'),
    path('<int:job_id>/competencies/', JobCompetencyConfigView.as_view(), name='job_competency_config'),
    path('<int:job_id>/assessment-plan/print/', JobAssessmentPlanPrintView.as_view(), name='job_assessment_plan_print'),
]
