# Generated by Django 5.2.15 on 2026-06-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstageplan',
            name='stage_type',
            field=models.CharField(choices=[('SCREENING', 'غربالگری'), ('EXAM', 'آزمون کتبی'), ('SKILL_TEST', 'آزمون مهارتی'), ('INTERVIEW', 'مصاحبه'), ('ASSESSMENT', 'کانون ارزیابی'), ('OTHER', 'سایر')], default='OTHER', max_length=20, verbose_name='نوع مرحله'),
        ),
        migrations.AlterField(
            model_name='stagetypeconfiguration',
            name='stage_type',
            field=models.CharField(choices=[('SCREENING', 'غربالگری'), ('EXAM', 'آزمون کتبی'), ('SKILL_TEST', 'آزمون مهارتی'), ('INTERVIEW', 'مصاحبه'), ('ASSESSMENT', 'کانون ارزیابی'), ('OTHER', 'سایر')], max_length=20, unique=True, verbose_name='نوع مرحله'),
        ),
    ]
