# Generated by Django 5.2.15 on 2026-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_planning', '0002_alter_jobstageplan_stage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstageplan',
            name='is_exact',
            field=models.BooleanField(default=False, verbose_name='روز دقیق ارزیابی'),
        ),
    ]
