# Generated by Django 5.2.15 on 2026-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان شغل')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد شغل')),
                ('department', models.CharField(max_length=100, verbose_name='بخش / واحد سازمانی')),
                ('description', models.TextField(verbose_name='شرح شغل و شرایط احراز')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال')], default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('weight_written_test', models.PositiveIntegerField(default=30, verbose_name='وزن آزمون کتبی (٪)')),
                ('weight_interview', models.PositiveIntegerField(default=40, verbose_name='وزن مصاحبه حضوری (٪)')),
                ('weight_assessment', models.PositiveIntegerField(default=30, verbose_name='وزن کانون ارزیابی (٪)')),
            ],
            options={
                'verbose_name': 'فرصت شغلی',
                'verbose_name_plural': 'فرصت\u200cهای شغلی',
                'ordering': ['-created_at'],
            },
        ),
    ]
