# Generated by Django 5.2.15 on 2026-06-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopportunity',
            name='weight_assessment',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='weight_interview',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='weight_written_test',
        ),
        migrations.CreateModel(
            name='EvaluationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='وزن (٪)')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.jobopportunity', verbose_name='فرصت شغلی')),
            ],
            options={
                'verbose_name': 'مرحله ارزیابی',
                'verbose_name_plural': 'مراحل ارزیابی',
                'ordering': ['sequence', 'created_at'],
            },
        ),
    ]
