# Generated by Django 5.2.15 on 2026-06-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobopportunitystage_stage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='source',
            field=models.CharField(choices=[('ATS', 'سیستم ATS'), ('IMPORT', 'ایمپورت شده')], default='ATS', max_length=10, verbose_name='منبع ایجاد'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='description',
            field=models.TextField(blank=True, verbose_name='شرح شغل'),
        ),
    ]
