# Generated by Django 5.2.15 on 2026-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobopportunity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunitystage',
            name='is_manually_completed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='وضعیت تکمیل دستی'),
        ),
    ]
