# Generated by Django 5.2.15 on 2026-06-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_jobopportunity_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('post_code', models.CharField(max_length=50, verbose_name='کد پست')),
                ('post_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='پست')),
                ('code', models.CharField(max_length=50, verbose_name='کد شایستگی')),
                ('old_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد شایستگی قدیم')),
                ('title', models.CharField(max_length=300, verbose_name='شایستگی')),
                ('competency_type', models.CharField(choices=[('KN', 'دانش (Knowledge)'), ('SK', 'مهارت (Skill)'), ('AB', 'توانایی (Ability)'), ('GE', 'رفتاری (General/Behavioral)'), ('ST', 'ارزش\u200cها و سبک\u200cها (Styles & Values)'), ('PR', 'گردشکار و فرآیندها (Process)'), ('CQ', 'گواهینامه\u200cها و صلاحیت\u200cها (Certification & Qualification)'), ('IN', 'علایق حرفه\u200cای (Interests)')], max_length=10, verbose_name='نوع شایستگی')),
                ('category_raw', models.CharField(blank=True, max_length=100, null=True, verbose_name='طبقه')),
                ('cluster_raw', models.CharField(blank=True, max_length=100, null=True, verbose_name='خوشه')),
                ('importance', models.PositiveIntegerField(choices=[(1, 'محوری'), (2, 'تکلیف محور'), (3, 'حداقلی')], verbose_name='اهمیت شایستگی')),
                ('level', models.PositiveIntegerField(choices=[(1, 'آشنایی'), (2, 'توانایی'), (3, 'تسلط')], verbose_name='سطح شایستگی')),
                ('management_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد مدیریت')),
                ('management_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='مدیریت')),
                ('vice_president_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد معاونت')),
                ('vice_president_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='معاونت')),
                ('section_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد قسمت')),
                ('section_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='قسمت')),
                ('cost_center_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد مرکز هزینه')),
                ('cost_center_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='مرکز هزینه')),
            ],
            options={
                'verbose_name': 'شایستگی مرجع',
                'verbose_name_plural': 'بانک شایستگی\u200cهای مرجع',
                'ordering': ['post_code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JobOpportunityCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('code', models.CharField(max_length=50, verbose_name='کد شایستگی')),
                ('title', models.CharField(max_length=300, verbose_name='شایستگی')),
                ('competency_type', models.CharField(choices=[('KN', 'دانش (Knowledge)'), ('SK', 'مهارت (Skill)'), ('AB', 'توانایی (Ability)'), ('GE', 'رفتاری (General/Behavioral)'), ('ST', 'ارزش\u200cها و سبک\u200cها (Styles & Values)'), ('PR', 'گردشکار و فرآیندها (Process)'), ('CQ', 'گواهینامه\u200cها و صلاحیت\u200cها (Certification & Qualification)'), ('IN', 'علایق حرفه\u200cای (Interests)')], max_length=10, verbose_name='نوع شایستگی')),
                ('importance', models.PositiveIntegerField(choices=[(1, 'محوری'), (2, 'تکلیف محور'), (3, 'حداقلی')], verbose_name='اهمیت شایستگی')),
                ('level', models.PositiveIntegerField(choices=[(1, 'آشنایی'), (2, 'توانایی'), (3, 'تسلط')], verbose_name='سطح شایستگی')),
                ('central_competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_links', to='jobs.centralcompetency', verbose_name='شایستگی مرجع')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_competencies', to='jobs.jobopportunity', verbose_name='فرصت شغلی')),
            ],
            options={
                'verbose_name': 'شایستگی فرصت شغلی',
                'verbose_name_plural': 'شایستگی\u200cهای فرصت شغلی',
                'ordering': ['job', 'code'],
            },
        ),
    ]
