# Generated by Django 5.2.15 on 2026-06-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_centralcompetency_jobopportunitycompetency'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunitycompetency',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='ایجاد دستی'),
        ),
    ]
