# Generated by Django 5.2.15 on 2026-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_organizationsetting_email_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralcompetency',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='کد شایستگی'),
        ),
        migrations.AlterField(
            model_name='centralcompetency',
            name='post_code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='کد پست'),
        ),
    ]
