# Generated by Django 5.2.15 on 2026-06-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_centralcompetency_is_organizational'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام مدل شایستگی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مدل شایستگی',
                'verbose_name_plural': 'مدل\u200cهای شایستگی',
            },
        ),
        migrations.AddField(
            model_name='jobopportunitycompetency',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدل شایستگی'),
        ),
        migrations.CreateModel(
            name='CompetencyModelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان شایستگی')),
                ('competency_type', models.CharField(choices=[('KN', 'دانش (Knowledge)'), ('SK', 'مهارت (Skill)'), ('AB', 'توانایی (Ability)'), ('GE', 'رفتاری (General/Behavioral)'), ('ST', 'ارزش\u200cها و سبک\u200cها (Styles & Values)')], default='GE', max_length=10, verbose_name='نوع شایستگی')),
                ('importance', models.PositiveIntegerField(choices=[(1, 'محوری'), (2, 'تکلیف محور'), (3, 'حداقلی')], default=1, verbose_name='اهمیت شایستگی')),
                ('level', models.PositiveIntegerField(choices=[(1, 'آشنایی'), (2, 'توانایی'), (3, 'تسلط')], default=2, verbose_name='سطح شایستگی')),
                ('code', models.CharField(default='MODEL', max_length=50, verbose_name='کد شایستگی')),
                ('competency_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.competencymodel', verbose_name='مدل شایستگی')),
            ],
            options={
                'verbose_name': 'شایستگی مدل',
                'verbose_name_plural': 'شایستگی\u200cهای مدل',
            },
        ),
    ]
