# Generated by Django 5.2.15 on 2026-07-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_organizationsetting_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='bypass_limits',
            field=models.BooleanField(default=False, verbose_name='بایپس کردن رنج'),
        ),
    ]
