# Generated by Django 5.2.15 on 2026-07-20 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_jobopportunity_bypass_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobopportunity',
            name='unique_code_active',
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='factory_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='کارخانه / محل استقرار'),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'دریافت شده'), ('PLANNING', 'برنامه‌ریزی'), ('PUBLISHED', 'منتشر شده'), ('REGISTRATION_CLOSED', 'خاتمه ثبت‌نام'), ('SCREENING', 'غربالگری اولیه'), ('EXAM', 'آزمون کتبی'), ('SKILL_TEST', 'آزمون مهارتی'), ('IQ_TEST', 'تست هوش'), ('INTERVIEW', 'مصاحبه حضوری'), ('ASSESSMENT', 'کانون ارزیابی'), ('FINAL_SELECTION', 'انتخاب نهایی'), ('CLOSED', 'اتمام یافته'), ('CANCELLED', 'لغو شده'), ('SUSPENDED', 'توقف موقت')], default='RECEIVED', max_length=30, verbose_name='وضعیت فرصت شغلی'),
        ),
        migrations.AlterField(
            model_name='jobopportunitystage',
            name='stage_type',
            field=models.CharField(choices=[('SCREENING', 'غربالگری'), ('EXAM', 'آزمون کتبی'), ('SKILL_TEST', 'آزمون مهارتی'), ('IQ_TEST', 'تست هوش'), ('INTERVIEW', 'مصاحبه'), ('ASSESSMENT', 'کانون ارزیابی'), ('OTHER', 'سایر')], default='OTHER', max_length=20, verbose_name='نوع مرحله'),
        ),
        migrations.AlterField(
            model_name='workflowstagetemplate',
            name='stage_type',
            field=models.CharField(choices=[('SCREENING', 'غربالگری'), ('EXAM', 'آزمون کتبی'), ('SKILL_TEST', 'آزمون مهارتی'), ('IQ_TEST', 'تست هوش'), ('INTERVIEW', 'مصاحبه'), ('ASSESSMENT', 'کانون ارزیابی'), ('OTHER', 'سایر')], default='OTHER', max_length=20, verbose_name='نوع مرحله'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='name',
            field=models.CharField(default='سیستم جذب', max_length=200, verbose_name='نام سازمان'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='exam_sms_body',
            field=models.TextField(default='متقاضی گرامی {{ candidate_name }}، دعوت‌نامه شرکت در آزمون کتبی شغل "{{ job_title }}" برای شما صادر شد.\nزمان آزمون: {{ date }} ساعت {{ time }}\nجزییات بیشتر و لینک شرکت در آزمون در پنل {{ company_name }}:\n{{ link }}', verbose_name='متن پیامک دعوت به آزمون'),
        ),
        migrations.AddConstraint(
            model_name='jobopportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('request_number', 'code'), name='unique_request_number_code_active', violation_error_message='یک فرصت شغلی فعال با این ترکیب شماره درخواست و کد شغل از قبل وجود دارد.'),
        ),
    ]
