# Generated by Django 5.2.16 on 2026-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_remove_jobopportunity_unique_code_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('job_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد شغل')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شغل')),
                ('job_level_type_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='رده شغلی نوع ۱')),
                ('sub_department_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام زیربخش')),
                ('job_family', models.CharField(blank=True, max_length=200, null=True, verbose_name='خانواده شغلی')),
                ('job_level_type_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='رده شغلی نوع ۲')),
                ('job_category', models.CharField(blank=True, max_length=200, null=True, verbose_name='رده شغلی')),
                ('job_nature', models.CharField(blank=True, max_length=100, null=True, verbose_name='ماهیت شغل')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='بخش / دپارتمان')),
                ('deputy', models.CharField(blank=True, max_length=200, null=True, verbose_name='معاونت')),
                ('higher_post_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پست بالاتر')),
                ('higher_post_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان پست بالاتر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح وظایف اصلاح\u200cشده')),
                ('job_type_details', models.TextField(blank=True, null=True, verbose_name='مشخصات و الزامات شغل')),
                ('related_jobs', models.TextField(blank=True, null=True, verbose_name='مشاغل مرتبط')),
                ('general_goal', models.TextField(blank=True, null=True, verbose_name='هدف و تعریف کلی شغل')),
                ('expected_results', models.TextField(blank=True, null=True, verbose_name='نتایج و پیامدهای مورد انتظار')),
            ],
            options={
                'verbose_name': 'شرح وظایف استاندارد',
                'verbose_name_plural': 'شرح وظایف\u200cهای استاندارد',
            },
        ),
    ]
