# Generated by Django 5.2.17 on 2026-09-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_jobopportunity_expected_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='custom_apply_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس اختصاصی پرتال ثبت\u200cنام / آگهی'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='default_ad_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='آدرس پیش\u200cفرض پرتال ثبت\u200cنام / آگهی\u200cهای استخدامی'),
        ),
    ]
