# Generated by Django 5.2.17 on 2026-09-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_jobopportunity_custom_apply_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='general_requirements',
            field=models.TextField(blank=True, default='', verbose_name='شرایط عمومی احراز (پیش\u200cفرض تمامی آگهی\u200cها)'),
        ),
    ]
