# Generated by Django 5.2.17 on 2026-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_organizationsetting_general_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='exam_default_time_per_question',
            field=models.FloatField(default=1.5, verbose_name='زمان پیش\u200cفرض هر سوال مرکز آزمون (دقیقه)'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='exam_default_total_questions',
            field=models.IntegerField(default=50, verbose_name='تعداد پیش\u200cفرض سوالات مرکز آزمون کتبی'),
        ),
    ]
