# Generated by Django 5.2.17 on 2026-09-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_organizationsetting_exam_default_time_per_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetting',
            name='exam_default_time_per_question',
            field=models.FloatField(blank=True, default=1.5, null=True, verbose_name='زمان پیش\u200cفرض هر سوال مرکز آزمون (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='exam_default_total_questions',
            field=models.IntegerField(blank=True, default=50, null=True, verbose_name='تعداد پیش\u200cفرض سوالات مرکز آزمون کتبی'),
        ),
    ]
