# Generated by Django 5.2.17 on 2026-09-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_jobopportunity_is_status_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی هماهنگ\u200cکننده')),
                ('personnel_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرسنلی')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیک (ایمیل)')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='شماره همراه')),
                ('bale_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه بله (Bale ID / Username / Chat ID)')),
                ('departments', models.JSONField(blank=True, default=list, help_text='لیست دپارتمان\u200cها یا نواحی سازمانی که این هماهنگ\u200cکننده مسئول آنهاست', verbose_name='نواحی / دپارتمان\u200cهای تحت پوشش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
            ],
            options={
                'verbose_name': 'هماهنگ\u200cکننده ناحیه',
                'verbose_name_plural': 'هماهنگ\u200cکنندگان نواحی',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='email_provider',
            field=models.CharField(choices=[('CUSTOM', 'ایجاد دستی (SMTP سفارشی)'), ('GMAIL', 'گوگل (Gmail)'), ('MSC', 'پست الکترونیک فولاد مبارکه (msc.ir)'), ('OUTLOOK', 'اوتلوک (Outlook)')], default='CUSTOM', max_length=30, verbose_name='سرویس\u200cدهنده ایمیل'),
        ),
    ]
