# Generated by Django 5.2.17 on 2026-09-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_areacoordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetting',
            name='bale_api_url',
            field=models.CharField(blank=True, default='https://tapi.bale.ai/bot', max_length=255, verbose_name='آدرس API ربات بله'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='bale_bot_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='توکن ربات بله (Bale Bot Token)'),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='bale_bot_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه کاربری ربات بله (Username)'),
        ),
    ]
