# Generated by Django 5.2.17 on 2026-09-11 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncPackageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='شناسه بسته')),
                ('direction', models.CharField(choices=[('OUTGOING', 'ارسال شده به سرور'), ('INCOMING', 'دریافت شده از سرور / فایل')], max_length=15, verbose_name='جهت انتقال')),
                ('author', models.CharField(max_length=200, verbose_name='کارشناس تولیدکننده')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان بسته')),
                ('summary', models.JSONField(default=dict, verbose_name='خلاصه تغییرات')),
                ('payload', models.JSONField(default=dict, verbose_name='محتوای بسته')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی و تایید'), ('MERGED', 'ادغام و اعمال شده در دیتابیس'), ('REJECTED', 'رد شده'), ('EXPORTED', 'ارسال / ذخیره شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('merge_report', models.JSONField(blank=True, null=True, verbose_name='گزارش ادغام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اعمال در دیتابیس')),
            ],
            options={
                'verbose_name': 'تاریخچه بسته همگام\u200cسازی',
                'verbose_name_plural': 'تاریخچه بسته\u200cهای همگام\u200cسازی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(default='https://zarfy.ir/ats-sync/api.php', verbose_name='آدرس وب\u200cسرویس همگام\u200cسازی (zarfy.ir)')),
                ('api_key', models.CharField(default='ats_secret_key_zarfy_2026', max_length=255, verbose_name='کلید امنیتی اتصال (API Key)')),
                ('specialist_name', models.CharField(default='کارشناس تامین سرمایه انسانی', max_length=200, verbose_name='نام و عنوان کارشناس جاری')),
                ('device_id', models.CharField(default=uuid.uuid4, max_length=100, verbose_name='شناسه یکتای دستگاه')),
                ('last_sync_check', models.DateTimeField(blank=True, null=True, verbose_name='آخرین زمان بررسی سرور')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات همگام\u200cسازی',
                'verbose_name_plural': 'تنظیمات همگام\u200cسازی',
            },
        ),
    ]
