# Generated by Django 5.2.15 on 2026-06-03 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'ویرایش'), ('DELETE', 'حذف'), ('SCORE_CHANGE', 'تغییر امتیاز'), ('STATUS_CHANGE', 'تغییر وضعیت')], max_length=20, verbose_name='نوع عملیات')),
                ('model_name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('object_id', models.CharField(max_length=255, verbose_name='شناسه شی')),
                ('changes', models.JSONField(verbose_name='تغییرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ حسابرسی',
                'verbose_name_plural': 'لاگ\u200cهای حسابرسی',
                'ordering': ['-timestamp'],
            },
        ),
    ]
