from django.urls import path
from .views import (
    CandidateListView,
    CandidateDetailView,
    CandidateCreateView,
    CandidateUpdateView,
    CandidateDeleteView,
    JobApplicationCreateView,
    JobOpportunityPipelineView,
    ToggleStageCompletionView,
    EditApplicationStageStateView,
    UpdateApplicationStageStateView,
    ViewApplicationStageStateView,
    UpdateApplicationStatusView,
    CareersListView,
    CareersDetailAndApplyView,
    CareersTrackView,
    CareersSuccessView,
    CandidateSignUpView,
    CandidateDashboardView,
    CandidateProfileUpdateView,
    CandidateEducationUpdateView,
    CandidateExperienceUpdateView,
    CandidateApplyDirectView,
    CandidateLanguageUpdateView,
    CandidateSkillUpdateView,
    CandidateCertificateUpdateView,
    ScoreEntryListView,
    InterviewsPanelView,
    SubmitInterviewerScoreView,
    ManageStageInterviewersView,
    JobOpportunityDescriptionView,
    AssessmentCenterSheetView,
    InterviewScoresPanelView,
    AssessmentCenterReportView,
    AssessmentCenterDetailReportView,
    JobOpportunityFinalRankingView,
    BulkUpdateApplicationStatusView,
    BulkAdvanceStageView,
    AssignCandidateToJobView,
    ExportCandidatesExcelView,
    ExportScoreEntryExcelView,
    ExportInterviewsExcelView,
    ExportAssessmentCenterExcelView,
    ExportJobFinalRankingExcelView,
    DownloadCandidateTemplateView,
    ImportCandidatesView,
    ImportScoreEntryExcelView,
    CandidatePasswordChangeView,
    CandidateResumePrintView,
    CandidateTranscriptPrintView,
    StageRollbackView,
    ManageJobDefaultInterviewersView,
    BulkInterviewScoresView,
    DownloadInterviewScoresTemplateView,
    ImportInterviewScoresExcelView,
    JobOpportunityReportView,
    DataIntegrityDashboardView,
    ResolveDiscrepancyView,
    UndoIntegrityActionView,
    SelectedCandidatesListView,
    EditAdmissionDateView,
    UpdateAdmissionDateView,
    CandidatesByStageListView,
    BulkSendNotificationModalView,
    BulkSendNotificationView,
)


urlpatterns = [
    path('', CandidateListView.as_view(), name='candidate_list'),
    path('selected/', SelectedCandidatesListView.as_view(), name='selected_candidates_list'),
    path('add/', CandidateCreateView.as_view(), name='candidate_add'),
    path('export/excel/', ExportCandidatesExcelView.as_view(), name='candidate_export_excel'),
    path('import/excel/', ImportCandidatesView.as_view(), name='candidate_import_excel'),
    path('import/template/', DownloadCandidateTemplateView.as_view(), name='candidate_import_template'),
    path('<int:pk>/', CandidateDetailView.as_view(), name='candidate_detail'),
    path('<int:pk>/resume/print/', CandidateResumePrintView.as_view(), name='candidate_resume_print'),
    path('<int:pk>/edit/', CandidateUpdateView.as_view(), name='candidate_edit'),
    path('<int:pk>/delete/', CandidateDeleteView.as_view(), name='candidate_delete'),
    path('application/<int:pk>/transcript/print/', CandidateTranscriptPrintView.as_view(), name='candidate_transcript_print'),
    
    path('score-entry/', ScoreEntryListView.as_view(), name='candidate_score_entry'),
    path('score-entry/export/excel/', ExportScoreEntryExcelView.as_view(), name='score_entry_export_excel'),
    path('score-entry/import/excel/', ImportScoreEntryExcelView.as_view(), name='score_entry_import_excel'),
    path('interviews/', InterviewsPanelView.as_view(), name='candidate_interviews'),
    path('interviews/export/excel/', ExportInterviewsExcelView.as_view(), name='interviews_export_excel'),
    path('interviews/<int:pk>/submit/', SubmitInterviewerScoreView.as_view(), name='candidate_submit_interviewer_score'),
    path('interviews/<int:pk>/assessment/', AssessmentCenterSheetView.as_view(), name='candidate_assessment_sheet'),
    path('interviews/<int:pk>/scores-panel/', InterviewScoresPanelView.as_view(), name='interview_scores_panel'),
    path('assessment-center/', AssessmentCenterReportView.as_view(), name='assessment_center_report'),
    path('assessment-center/export/excel/', ExportAssessmentCenterExcelView.as_view(), name='assessment_center_export_excel'),
    path('assessment-center/<int:pk>/report/', AssessmentCenterDetailReportView.as_view(), name='assessment_center_detail_report'),
    path('opportunity/stage/<int:stage_id>/interviewers/', ManageStageInterviewersView.as_view(), name='manage_stage_interviewers'),
    path('opportunity/<int:pk>/description/', JobOpportunityDescriptionView.as_view(), name='job_opportunity_description'),
    
    path('<int:candidate_id>/apply/', JobApplicationCreateView.as_view(), name='candidate_apply'),
    path('<int:candidate_id>/assign-job/', AssignCandidateToJobView.as_view(), name='assign_candidate_job'),
    
    path('opportunity/<int:pk>/pipeline/', JobOpportunityPipelineView.as_view(), name='job_pipeline'),
    path('opportunity/<int:pk>/ranking/', JobOpportunityFinalRankingView.as_view(), name='job_final_ranking'),
    path('opportunity/<int:pk>/ranking/export/excel/', ExportJobFinalRankingExcelView.as_view(), name='job_ranking_export_excel'),
    path('opportunity/<int:job_id>/pipeline/bulk-status/', BulkUpdateApplicationStatusView.as_view(), name='bulk_update_application_status'),
    path('opportunity/<int:job_id>/pipeline/bulk-advance/', BulkAdvanceStageView.as_view(), name='bulk_advance_stage'),
    path('opportunity/stage/<int:stage_id>/toggle-completion/', ToggleStageCompletionView.as_view(), name='toggle_stage_completion'),
    path('stage-state/<int:pk>/edit/', EditApplicationStageStateView.as_view(), name='edit_stage_state'),
    path('stage-state/<int:pk>/update/', UpdateApplicationStageStateView.as_view(), name='update_stage_state'),
    path('stage-state/<int:pk>/view/', ViewApplicationStageStateView.as_view(), name='view_stage_state'),
    path('application/<int:pk>/status/', UpdateApplicationStatusView.as_view(), name='update_application_status'),
    path('application/<int:app_id>/stage/<int:stage_id>/rollback/', StageRollbackView.as_view(), name='stage_rollback'),

    path('opportunity/<int:job_id>/default-interviewers/', ManageJobDefaultInterviewersView.as_view(), name='manage_default_interviewers'),
    path('score-entry/bulk-interview/', BulkInterviewScoresView.as_view(), name='bulk_interview_scores'),
    path('score-entry/interview-scores/template/', DownloadInterviewScoresTemplateView.as_view(), name='download_interview_scores_template'),
    path('score-entry/interview-scores/import/', ImportInterviewScoresExcelView.as_view(), name='import_interview_scores'),
    path('opportunity/<int:pk>/report/', JobOpportunityReportView.as_view(), name='job_opportunity_report'),
    


    path('careers/', CareersListView.as_view(), name='careers_list'),
    path('careers/<int:pk>/', CareersDetailAndApplyView.as_view(), name='careers_apply'),
    path('careers/track/', CareersTrackView.as_view(), name='careers_track'),
    path('careers/success/', CareersSuccessView.as_view(), name='careers_success'),
    
    # Candidate Auth & Dashboard URLs
    path('signup/', CandidateSignUpView.as_view(), name='candidate_signup'),
    path('dashboard/', CandidateDashboardView.as_view(), name='candidate_dashboard'),
    path('profile/update/', CandidateProfileUpdateView.as_view(), name='candidate_profile_update'),
    path('education/update/', CandidateEducationUpdateView.as_view(), name='candidate_education_update'),
    path('experience/update/', CandidateExperienceUpdateView.as_view(), name='candidate_experience_update'),
    path('language/update/', CandidateLanguageUpdateView.as_view(), name='candidate_language_update'),
    path('skill/update/', CandidateSkillUpdateView.as_view(), name='candidate_skill_update'),
    path('certificate/update/', CandidateCertificateUpdateView.as_view(), name='candidate_certificate_update'),
    path('apply/<int:pk>/', CandidateApplyDirectView.as_view(), name='candidate_apply_direct'),
    path('password/change/', CandidatePasswordChangeView.as_view(), name='candidate_password_change'),
    
    path('data-integrity/', DataIntegrityDashboardView.as_view(), name='data_integrity_dashboard'),
    path('data-integrity/resolve/', ResolveDiscrepancyView.as_view(), name='resolve_discrepancy'),
    path('data-integrity/undo/<int:log_id>/', UndoIntegrityActionView.as_view(), name='undo_integrity_action'),
    
    path('application/<int:pk>/edit-admission-date/', EditAdmissionDateView.as_view(), name='edit_admission_date'),
    path('application/<int:pk>/update-admission-date/', UpdateAdmissionDateView.as_view(), name='update_admission_date'),
    path('by-stage/', CandidatesByStageListView.as_view(), name='candidates_by_stage_list'),
    path('opportunity/<int:job_id>/pipeline/bulk-send-notification-modal/', BulkSendNotificationModalView.as_view(), name='bulk_send_notification_modal'),
    path('opportunity/<int:job_id>/pipeline/bulk-send-notification/', BulkSendNotificationView.as_view(), name='bulk_send_notification'),
]

