# Generated by Django 5.2.15 on 2026-06-09 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0009_applicationstagestate_is_conditional_pass'),
        ('jobs', '0011_jobopportunitystage_stage_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('excel_file', models.FileField(upload_to='historical_imports/', verbose_name='فایل اکسل سوابق')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تحلیل'), ('ANALYZED', 'تحلیل شده'), ('MAPPED', 'نگاشت شده'), ('PREVIEWED', 'پیش\u200cنمایش شده'), ('COMPLETED', 'ایمپورت موفقیت\u200cآمیز'), ('FAILED', 'خطا در فرآیند ایمپورت')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('mapping_config', models.JSONField(blank=True, null=True, verbose_name='پیکربندی نگاشت')),
                ('summary_data', models.JSONField(blank=True, null=True, verbose_name='خلاصه آمار')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد کننده')),
            ],
            options={
                'verbose_name': 'نشست ورود سوابق',
                'verbose_name_plural': 'نشست\u200cهای ورود سوابق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('level', models.CharField(choices=[('INFO', 'اطلاعات'), ('WARNING', 'هشدار'), ('ERROR', 'خطا')], default='INFO', max_length=10, verbose_name='سطح لاگ')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('sheet_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شیت')),
                ('row_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره ردیف')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='historical_import.importsession', verbose_name='نشست ورود')),
            ],
            options={
                'verbose_name': 'لاگ نشست ورود',
                'verbose_name_plural': 'لاگ\u200cهای نشست ورود',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StagingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100, verbose_name='نام شیت')),
                ('row_index', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('job_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد فرصت شغلی')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد ملی')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن تماس')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('score', models.CharField(blank=True, max_length=50, null=True, verbose_name='امتیاز')),
                ('evaluation_date_str', models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ ارزیابی')),
                ('stage_type', models.CharField(max_length=50, verbose_name='نوع مرحله')),
                ('raw_data', models.JSONField(default=dict, verbose_name='داده\u200cهای خام')),
                ('is_valid', models.BooleanField(default=True, verbose_name='معتبر است؟')),
                ('validation_errors', models.JSONField(default=list, verbose_name='خطاهای اعتبارسنجی')),
                ('validation_warnings', models.JSONField(default=list, verbose_name='هشدارهای اعتبارسنجی')),
                ('final_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate', verbose_name='متقاضی نهایی')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_candidates', to='historical_import.importsession', verbose_name='نشست ورود')),
            ],
            options={
                'verbose_name': 'متقاضی موقت',
                'verbose_name_plural': 'متقاضیان موقت',
                'ordering': ['sheet_name', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='StagingJobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(verbose_name='شماره ردیف')),
                ('job_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد شغل')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان شغل')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='دپارتمان / واحد')),
                ('headcount', models.CharField(blank=True, max_length=50, null=True, verbose_name='تعداد مورد نیاز')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت')),
                ('start_date_str', models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ شروع')),
                ('workflow_pattern', models.CharField(blank=True, max_length=255, null=True, verbose_name='الگوی استخدام')),
                ('raw_data', models.JSONField(default=dict, verbose_name='داده\u200cهای خام')),
                ('is_valid', models.BooleanField(default=True, verbose_name='معتبر است؟')),
                ('validation_errors', models.JSONField(default=list, verbose_name='خطاهای اعتبارسنجی')),
                ('validation_warnings', models.JSONField(default=list, verbose_name='هشدارهای اعتبارسنجی')),
                ('final_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobopportunity', verbose_name='فرصت شغلی نهایی')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_jobs', to='historical_import.importsession', verbose_name='نشست ورود')),
            ],
            options={
                'verbose_name': 'فرصت شغلی موقت',
                'verbose_name_plural': 'فرصت\u200cهای شغلی موقت',
                'ordering': ['row_index'],
            },
        ),
    ]
