# Generated by Django 5.2.15 on 2026-06-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='assessment_date_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ کانون ارزیابی'),
        ),
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='شرح شغل'),
        ),
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='exam_date_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ آزمون کتبی'),
        ),
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='interview_date_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ مصاحبه'),
        ),
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='job_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رده شغلی'),
        ),
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای داخلی'),
        ),
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='screening_date_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ غربالگری'),
        ),
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='skill_test_date_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ آزمون مهارتی'),
        ),
        migrations.AddField(
            model_name='stagingjobopportunity',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد سازمانی'),
        ),
    ]
