# -*- coding: utf-8 -*-

TRANSLATIONS = {
    'fa': {
        'dashboard': 'داشبورد',
        'jobs': 'فرصت‌های شغلی',
        'workflows': 'الگوهای فرآیند استخدام',
        'candidates': 'متقاضیان',
        'candidates_by_stage': 'پایش متقاضیان به تفکیک مراحل',
        'planning': 'برنامه‌ریزی جذب',
        'analytics': 'داشبورد تحلیلی و گزارشات',
        'competencies': 'شایستگی‌ها',
        'competency_bank': 'بانک شایستگی‌ها',
        'competency_models': 'مدل‌های شایستگی',
        'custom_competencies': 'شایستگی‌های دستی',
        'recruitment_patterns': 'الگوهای استخدامی',
        'upload_excel': 'بارگذاری اکسل شایستگی',
        'score_entry': 'ثبت و ورود نمرات',
        'interviews_panel': 'پنل مصاحبه‌ها',
        'assessment_pdf': 'کانون ارزیابی (PDF)',
        'talent_bank': 'بانک استعدادها',
        'settings': 'تنظیمات سیستم',
        'preferences': 'شخصی‌سازی ظاهر',
        'import_records': 'ایمپورت سوابق (اکسل)',
        'rbac': 'مدیریت کاربران (RBAC)',
        'backup': 'پشتیبان‌گیری و بازگردانی',
        'data_integrity': 'پایش سلامت داده‌ها',
        'ai_settings': 'تنظیمات هوش مصنوعی',
        'org_settings': 'تنظیمات سازمان',
        'audit_logs': 'لاگ‌های ممیزی (Audit Logs)',
        'logout': 'خروج',
        'welcome': 'خوش آمدید',
        'system_title': 'سیستم جذب',
        'sidebar_title': 'سیستم جذب',
        'written_spec': 'مشخصات آزمون کتبی',
        'lang_label': 'انتخاب زبان',
        
        # Dashboard Translations
        'workspace': 'میز کار الکترونیک',
        'dashboard_welcome': 'سلام {name} — نمای لحظه‌ای وضعیت فرآیند جذب',
        'print_pdf': '🖨️ چاپ داشبورد / خروجی PDF',
        'active_opportunities': 'فرصت‌های فعال',
        'in_flow': 'در جریان',
        'candidates_assessing': 'متقاضیان در ارزیابی',
        'active_status': 'فعال',
        'selected_candidates_kpi': 'پذیرفته‌شدگان نهایی',
        'hired_kpi': 'استخدام شده',
        'total_unique_candidates': 'کل متقاضیان یکتا',
        'resume_bank_kpi': 'بانک رزومه',
        'pipeline_title': 'تغییرات فازهای استخدامی (خط لوله جذب)',
        'pipeline_stage': 'مرحله',
        'pipeline_candidates': 'متقاضیان',
        'pipeline_percentage': 'درصد',
        'out_of_total_jobs': 'از کل {total} فرصت شغلی',
        'out_of_total_candidates': 'از کل {total} متقاضی',
        'history_btn': '🕒 تاریخچه فعالیت‌ها',
        'jobs_btn': '📋 فرصت‌های شغلی',
        'enter_scores': '✏️ ورود نمرات',
        
        # Job Management Page Translations
        'job_management_title': 'مدیریت فرصت‌های شغلی',
        'job_sub': 'تعریف فرصت‌های شغلی جدید و تنظیم مراحل و وزن‌های پویای فرآیند ارزیابی متقاضیان',
        'export_excel': 'خروجی اکسل',
        'bulk_status': 'تغییر وضعیت دسته‌جمعی',
        'add_job': 'افزودن فرصت شغلی جدید',
        'search_job': 'جستجوی فرصت شغلی',
        'search_placeholder': 'عنوان، کد شغل یا شماره درخواست...',
        'department_label': 'دپارتمان',
        'all_departments': 'همه دپارتمان‌ها',
        'unit_label': 'واحد سازمانی',
        'all_units': 'همه واحدها',
        'status_label': 'وضعیت',
        'all_statuses': 'همه وضعیت‌ها',
        'recruitment_type_label': 'نوع استخدام',
        'all_types': 'همه موارد',
        'category_label': 'رده شغلی',
        'all_categories': 'همه رده‌ها',
        'source_label': 'منبع ایجاد',
        'all_sources': 'همه منابع',
        'apply_filters': 'اعمال فیلترها',
        'clear_filters': 'پاک کردن',
        'code_th': 'کد شغل',
        'request_th': 'شماره درخواست',
        'title_th': 'عنوان شغل',
        'dept_th': 'دپارتمان / واحد',
        'date_th': 'تاریخ دریافت',
        'headcount_th': 'ظرفیت جذب',
        'type_th': 'نوع استخدام',
        'candidates_th': 'متقاضیان ثبت‌نامی',
        'stages_th': 'مراحل و ضرایب ارزیابی (به ترتیب فرآیند)',
        'status_th': 'وضعیت',
        'actions_th': 'عملیات',
        'request_lbl': 'درخواست:',
        'persons': 'نفر',
        'options': 'گزینه‌ها',
        'pipeline': 'پایپلاین',
        'no_data': 'اطلاعاتی موجود نیست.',
        'job_cat_legend': '👥 متقاضیان فعال در مراحل ارزیابی',
        'avg_days_legend': '⏱️ میانگین روزهای حضور در هر مرحله',
        'job_level_legend': '🎖️ متقاضیان فعال بر اساس رده شغلی',
        'job_status_legend': '📊 وضعیت فرصت‌های شغلی',
        'job_dist_legend': '📂 توزیع بر اساس رده شغلی',
        'cand_status_legend': '📈 وضعیت پرونده‌های متقاضیان',
        'job_ass_int_legend': '🎯 فرصت‌های در مرحله ارزیابی و مصاحبه',
        'view_all_jobs': 'مشاهده همه فرصت‌ها ←',
        'no_active_jobs_err': 'فرصت شغلی فعالی در مراحل کانون/مصاحبه یافت نشد.',
        'delayed_candidates_legend': '⚠️ متقاضیان خارج از SLA (دارای تأخیر)',
        'sla_dashboard_btn': 'میز کار تاخیرات SLA ←',
        'warning_badge': 'هشدار',
        'pass_badge': 'قبول',

        # --- Phase 2 Additions ---
        'wf_add_new': 'افزودن الگوی جدید',
        'wf_name': 'نام الگو',
        'wf_description': 'توضیحات الگو',
        'wf_default_stages': 'مراحل پیش‌فرض و ضرایب ارزیابی',
        'wf_no_desc': 'توضیحی ثبت نشده است.',
        'wf_no_stages': 'بدون مرحله پیش‌فرض',
        'wf_confirm_delete': 'آیا از حذف این الگوی فرآیند مطمئن هستید؟',
        'wf_empty_list': 'هیچ الگوی فرآیندی در سیستم تعریف نشده است.',
        'edit': 'ویرایش',
        'delete': 'حذف',
        'cancel': 'انصراف',
        'cand_mgmt': 'مدیریت متقاضیان',
        'cand_mgmt_sub': 'مشاهده، ویرایش و مدیریت تمامی پرونده‌های متقاضیان کار در سیستم',
        'talent_bank_adv': 'بانک استعداد پیشرفته (Talent Pool)',
        'talent_bank_sub': 'مدیریت، فیلتر هوشمند و انتساب مستقیم متقاضیان به فرصت‌های شغلی',
        'import_excel': 'ورود از اکسل',
        'add_candidate': 'افزودن متقاضی جدید',
        'kpi_total_talents': 'کل استعدادها در بانک',
        'kpi_higher_edu': 'سهم تحصیلات عالی (ارشد و دکتری)',
        'kpi_avg_exp': 'میانگین سابقه کار متقاضیان',
        'years_exp': 'سال',
        'search_candidate_placeholder': 'جستجو بر اساس نام، نام خانوادگی، کد ملی یا ایمیل...',
        'search_btn': 'جستجو',
        'adv_filters_btn': '➕ فیلترهای پیشرفته تحصیلی، سوابق و مهارت‌ها',
        'degree_label': 'مقطع تحصیلی:',
        'degree_all': 'همه مقاطع',
        'degree_assoc': 'کاردانی',
        'degree_bach': 'کارشناسی',
        'degree_master': 'کارشناسی ارشد',
        'degree_phd': 'دکتری',
        'major_label': 'رشته تحصیلی:',
        'major_placeholder': 'مثلاً: مهندسی کامپیوتر',
        'skill_label': 'مهارت:',
        'skill_placeholder': 'مثلاً: Python',
        'min_exp_label': 'حداقل سابقه کار (سال):',
        'min_exp_placeholder': 'مثلاً: ۳',
        'min_exam_score_label': 'حداقل نمره آزمون کتبی:',
        'min_exam_placeholder': 'مثلاً: ۷۵',
        'min_interview_score_label': 'حداقل نمره مصاحبه حضوری:',
        'min_interview_placeholder': 'مثلاً: ۸۰',
        'min_assessment_score_label': 'حداقل نمره کانون ارزیابی:',
        'min_assessment_placeholder': 'مثلاً: ۷۰',
        'applied_job_filter_label': 'فیلتر بر اساس فرصت شغلی درخواست‌شده:',
        'applied_job_placeholder': '-- انتخاب فرصت شغلی --',
        'smart_recommendation_label': '🧠 پیشنهاددهی هوشمند متقاضیان مناسب برای شغل:',
        'smart_recommendation_placeholder': '-- انتخاب شغل جهت تحلیل و رتبه‌بندی انطباق --',
        'clear_filters_btn': 'پاک کردن فیلترها',
        'apply_adv_filters_btn': 'اعمال فیلترهای پیشرفته',
        'cand_name_th': 'نام و نام خانوادگی',
        'cand_national_id_th': 'کد ملی / پرسنلی',
        'cand_contact_th': 'اطلاعات تماس',
        'cand_active_apps_th': 'درخواست‌های فعال',
        'cand_personnel_lbl': 'پرسنلی:',
        'cand_exam_lbl': 'آزمون:',
        'cand_interview_lbl': 'مصاحبه:',
        'cand_assessment_lbl': 'کانون:',
        'cand_apps_count': 'درخواست',
        'cand_match_score': 'انطباق',
        'assign_job_btn': '🔗 انتساب به شغل',
        'view_profile_btn': 'مشاهده پرونده',
        'cand_delete_confirm': 'آیا از حذف این متقاضی و تمامی سوابق وی مطمئن هستید؟',
        'cand_empty_list': 'متقاضی با مشخصات مورد نظر یافت نشد.',
        'showing_candidates': 'نمایش {start} تا {end} از {total} متقاضی',
        'modal_assign_title': 'انتساب متقاضی به فرصت شغلی فعال',
        'modal_assign_text': 'انتساب متقاضی {name} به فرصت‌های شغلی فعال به عنوان ثبت درخواست همکاری انجام می‌شود.',
        'modal_assign_select_lbl': 'فرصت شغلی مورد نظر را انتخاب کنید:',
        'modal_assign_select_placeholder': '-- انتخاب فرصت شغلی فعال --',
        'modal_assign_no_jobs': 'هیچ فرصت شغلی فعالی در سیستم وجود ندارد.',
        'modal_assign_submit': 'ثبت انتساب و شروع ارزیابی',
        'modal_import_title': 'ورود گروهی متقاضیان از اکسل',
        'modal_import_text': 'شما می‌توانید متقاضیان را به صورت گروهی از طریق بارگذاری یک فایل اکسل وارد سیستم نمایید. برای اطمینان از صحت وارد شدن اطلاعات، لطفاً ابتدا فایل نمونه را دانلود و تکمیل کنید.',
        'modal_import_download_template': 'دانلود فایل اکسل نمونه / الگو',
        'modal_import_job_select_lbl': 'فرصت شغلی انتسابی (اختیاری):',
        'modal_import_job_select_placeholder': '-- ثبت در بانک استعدادهای عمومی (بدون انتساب شغل) --',
        'modal_import_file_lbl': 'انتخاب فایل اکسل (.xlsx):',
        'modal_import_submit': 'بارگذاری و ثبت متقاضیان',
        'stage_track_title': 'پایش متقاضیان به تفکیک مراحل ارزیابی',
        'stage_track_sub': 'لیست تمامی متقاضیان در جریان ارزیابی فعال با امکان تفکیک و رصد مرحله فعلی',
        'stage_track_breadcrumbs': 'پایش متقاضیان به تفکیک مراحل',
        'back_to_dashboard': 'بازگشت به داشبورد',
        'export_excel_btn': 'خروجی اکسل (Excel)',
        'kpi_total_assessing': 'کل در حال ارزیابی',
        'kpi_screening': 'غربالگری',
        'search_track_placeholder': 'جستجو نام، کدملی، کدشغل...',
        'filter_stage_placeholder': '-- فیلتر مرحله ارزیابی --',
        'filter_job_placeholder': '-- فیلتر فرصت شغلی --',
        'filter_dept_placeholder': '-- فیلتر دپارتمان --',
        'apply_btn': 'اعمال',
        'table_th_stage': 'مرحله ارزیابی جاری',
        'table_th_score': 'امتیاز کل',
        'table_th_last_activity': 'آخرین فعالیت',
        'start_process': 'شروع فرآیند',
        'empty_track_list': 'هیچ کاندیدایی در حال ارزیابی با مشخصات وارد شده یافت نشد.',
        'showing_track_candidates': 'نمایش {start} تا {end} از {total} متقاضی در حال ارزیابی',
        'planning_title': 'برنامه‌ریزی و ظرفیت‌سنجی جذب',
        'planning_sub': 'مدیریت تقویم استخدام، کنترل تعهدات SLA مراحل و بررسی ظرفیت ماهانه ارزیاب‌ها',
        'planning_gantt_conflict': '🔍 پایش همزمانی و تداخل‌ها',
        'planning_calendar_btn': '📅 تقویم برنامه‌ریزی جذب',
        'planning_excel_btn': '📥 خروجی اکسل برنامه‌ها',
        'planning_config_btn': '⚙️ تنظیمات SLA و ظرفیت‌ها',
        'kpi_active_plans': 'برنامه‌های فعال',
        'kpi_delayed_plans': 'خارج از SLA (دارای تأخیر)',
        'kpi_draft_plans': 'برنامه‌های پیش‌نویس',
        'kpi_today_jalali': 'تاریخ امروز (شمسی)',
        'planning_active_badge': 'ACTIVE',
        'planning_delayed_badge': 'DELAYED',
        'planning_draft_badge': 'DRAFT',
        'planning_today_badge': 'TODAY',
        'planning_job_unit': 'فرصت شغلی',
        'planning_plan_unit': 'برنامه',
        'planning_capacity_monthly': 'پایش ظرفیت مراحل ارزیابی در ماه ({month})',
        'planning_prev_month': '◀ ماه قبل',
        'planning_next_month': 'ماه بعد ▶',
        'planning_candidate_limit': '{consumed} / {limit} متقاضی',
        'planning_remaining_capacity': 'ظرفیت باقیمانده: <strong>{remaining} نفر</strong>',
        'planning_consumed_percentage': '{percentage}٪ مصرف شده',
        'planning_agenda_title': '📅 دستور کار ۷ روز آینده',
        'planning_agenda_sub': 'شروع و پایان مراحل ارزیابی بر اساس برنامه‌ریزی‌های فعال در یک هفته پیش‌رو',
        'planning_agenda_excel': '📥 خروجی اکسل هفتگی',
        'planning_agenda_print': '🖨 چاپ / PDF هفتگی',
        'planning_agenda_start': 'شروع',
        'planning_agenda_end': 'پایان',
        'planning_agenda_stage_text': 'مرحله <strong class="text-dark">{stage}</strong> برای شغل <strong>{job}</strong>',
        'planning_no_agenda': 'هیچ رویدادی برای ۷ روز آینده زمانبندی نشده است.',
        'planning_unplanned_jobs_title': 'مشاغل بدون برنامه‌ریزی',
        'planning_unplanned_jobs_sub': 'فرصت‌های شغلی فعالی که هنوز برنامه زمانبندی جذب آن‌ها ثبت نشده است.',
        'planning_unplanned_code_headcount': 'کد: {code} | تعداد جذب: {headcount}',
        'planning_unplanned_btn': '📅 برنامه‌ریزی',
        'planning_all_planned_msg': 'همه فرصت‌های شغلی فعال برنامه‌ریزی شده‌اند.',
        'planning_active_plans_title': 'برنامه‌های استخدام فعال و تقویم فرآیندها',
        'planning_filter_active_badge': 'فیلتر فعال',
        'planning_search_placeholder': 'جستجوی عنوان شغل یا کد شغل...',
        'planning_all_depts_placeholder': 'همه دپارتمان‌ها / واحدها',
        'planning_sort_newest': 'جدیدترین برنامه‌ها',
        'planning_sort_oldest': 'قدیمی‌ترین برنامه‌ها',
        'planning_sort_start_asc': 'تاریخ شروع فرآیند (قدیمی به جدید)',
        'planning_sort_start_desc': 'تاریخ شروع فرآیند (جدید به قدیمی)',
        'planning_sort_end_asc': 'پایان پیش‌بینی‌شده (صعودی)',
        'planning_sort_end_desc': 'پایان پیش‌بینی‌شده (نزولی)',
        'planning_sort_title': 'عنوان شغل (الفبا)',
        'planning_sort_headcount': 'ظرفیت جذب (بیشترین)',
        'planning_filter_submit': 'اعمال فیلتر',
        'planning_headcount_lbl': 'تعداد موردنیاز: <strong class="text-primary">{count} نفر</strong>',
        'planning_start_lbl': 'شروع: <strong>{date}</strong>',
        'planning_end_lbl': 'پایان پیش‌بینی‌شده: <strong class="text-success">{date}</strong>',
        'planning_edit_btn': '📝 ویرایش زمانبندی',
        'planning_pipeline_btn': '📊 ورود به پایپلاین ارزیابی',
        'planning_empty_plans_msg': 'هیچ برنامه زمانبندی استخدام فعالی در سیستم ثبت نشده است.',
        'planning_empty_plans_sub': 'فرصت‌های شغلی را از جدول سمت راست بالای صفحه برنامه‌ریزی کنید.',

        # --- Phase 3 Additions ---
        # Candidate Detail
        'cd_title': 'پروفایل متقاضی:',
        'cd_back': 'بازگشت به لیست متقاضیان',
        'cd_sub': 'نمایش کامل سوابق هویتی، تحصیلی، کاری و تاریخچه ارزیابی‌های استخدامی',
        'cd_new_app': 'ثبت درخواست جدید (انتساب به شغل)',
        'cd_print_resume': 'چاپ رزومه',
        'cd_edit_candidate': 'ویرایش متقاضی',
        'cd_national_id': 'کد ملی:',
        'cd_personnel_number': 'شماره پرسنلی:',
        'cd_phone': 'شماره تماس',
        'cd_email': 'آدرس ایمیل',
        'cd_created_at': 'تاریخ ثبت‌نام در سامانه',
        'cd_download_resume': 'دانلود فایل رزومه',
        'cd_no_resume': 'فاقد فایل رزومه آپلود شده',
        'cd_edu_title': 'سوابق تحصیلی',
        'cd_graduation': 'فارغ‌التحصیلی:',
        'cd_gpa': 'معدل:',
        'cd_no_edu': 'سابقه تحصیلی ثبت نشده است.',
        'cd_exp_title': 'سوابق کاری',
        'cd_exp_range': 'بازه:',
        'cd_now': 'اکنون',
        'cd_no_exp': 'سابقه کاری ثبت نشده است.',
        'cd_skills_title': 'مهارت‌ها و زبان‌های خارجی',
        'cd_skills_sub': 'مهارت‌های تخصصی',
        'cd_no_skill': 'مهارتی ثبت نشده است.',
        'cd_langs_sub': 'زبان‌های خارجی',
        'cd_no_lang': 'زبانی ثبت نشده است.',
        'cd_certs_title': 'دوره‌ها و گواهینامه‌ها',
        'cd_certs_date': 'اخذ:',
        'cd_certs_exp': 'انقضا:',
        'cd_certs_no_exp': 'بدون تاریخ انقضا',
        'cd_no_certs': 'دوره یا گواهینامه‌ای ثبت نشده است.',
        'cd_apps_title': 'تاریخچه درخواست‌های همکاری',
        'cd_apps_job': 'فرصت شغلی',
        'cd_apps_date': 'تاریخ درخواست',
        'cd_apps_stage': 'مرحله ارزیابی جاری',
        'cd_apps_score': 'امتیاز کل',
        'cd_apps_status': 'وضعیت کل',
        'cd_apps_transcript': 'کارنامه ارزیابی',
        'cd_no_apps': 'هنوز هیچ درخواستی برای این متقاضی ثبت نشده است.',

        # Candidate Form
        'cf_edit_title': 'ویرایش متقاضی:',
        'cf_add_title': 'افزودن متقاضی جدید',
        'cf_edit_sub': 'ویرایش پرونده متقاضی:',
        'cf_add_sub': 'ثبت متقاضی جدید',
        'cf_desc': 'اطلاعات شناسنامه‌ای، تحصیلی و سوابق کاری متقاضی را وارد کنید',
        'cf_errors': 'لطفاً خطاهای موجود در فرم را بررسی و اصلاح فرمایید.',
        'cf_section_general': '۱. اطلاعات عمومی و هویتی',
        'cf_first_name': 'نام',
        'cf_last_name': 'نام خانوادگی',
        'cf_national_id': 'کد ملی',
        'cf_personnel': 'شماره پرسنلی (برای همکاران داخلی)',
        'cf_phone': 'شماره تماس',
        'cf_email': 'پست الکترونیکی',
        'cf_resume': 'فایل رزومه (PDF یا Word)',
        'cf_current_file': 'فایل فعلی:',
        'cf_view_resume': 'مشاهده رزومه فعلی',
        'cf_section_edu': '۲. سوابق تحصیلی',
        'cf_add_edu': 'افزودن سابقه تحصیلی',
        'cf_degree': 'مقطع تحصیلی',
        'cf_major': 'رشته تحصیلی',
        'cf_univ': 'دانشگاه / موسسه',
        'cf_gpa': 'معدل',
        'cf_grad_year': 'سال فارغ‌التحصیلی',
        'cf_delete_row': 'حذف سابقه',
        'cf_section_exp': '۳. سوابق کاری',
        'cf_add_exp': 'افزودن سابقه کاری',
        'cf_company': 'نام سازمان / شرکت',
        'cf_job_title': 'عنوان شغلی',
        'cf_start_date': 'تاریخ شروع (شمسی)',
        'cf_end_date': 'تاریخ پایان (شمسی)',
        'cf_exp_desc': 'توضیحات و دستاوردها',
        'cf_save': 'ذخیره تغییرات',
        'cf_create': 'ایجاد متقاضی',

        # Job Form
        'jf_edit_title': 'ویرایش فرصت شغلی',
        'jf_add_title': 'افزودن فرصت شغلی جدید',
        'jf_edit_sub': 'ویرایش فرصت شغلی:',
        'jf_desc': 'اطلاعات فرصت شغلی و مراحل فرآیند ارزیابی متقاضیان را مشخص کنید',
        'jf_section_general': '۱. اطلاعات عمومی فرصت شغلی',
        'jf_req_num': 'شماره درخواست',
        'jf_code': 'کد شغل',
        'jf_title': 'عنوان شغل',
        'jf_dept': 'بخش / دپارتمان',
        'jf_unit': 'واحد سازمانی',
        'jf_cat': 'رده شغلی',
        'jf_headcount': 'ظرفیت جذب (تعداد)',
        'jf_type': 'نوع استخدام',
        'jf_section_planning': '۲. برنامه‌ریزی و زمان‌بندی',
        'jf_recruiter': 'کارشناس جذب مسئول',
        'jf_workflow': 'الگوی فرآیند استخدامی (Workflow)',
        'jf_workflow_help': 'با انتخاب الگو، مراحل فرآیند به صورت خودکار تخصیص می‌یابند.',
        'jf_status': 'وضعیت فرصت شغلی',
        'jf_start_date': 'تاریخ شروع',
        'jf_end_date': 'تاریخ پایان',
        'jf_section_competencies': '۳. شایستگی‌های مورد ارزیابی',
        'jf_competencies_help': 'شایستگی‌های موردنیاز برای این شغل را انتخاب کنید. این شایستگی‌ها مبنای ارزیابی در کانون ارزیابی خواهند بود.',
        'jf_section_stages': '۴. مدیریت مراحل و اوزان ارزیابی',
        'jf_stages_help': 'مراحل ارزیابی این فرصت شغلی و ضرایب (وزن) هر مرحله را مشخص کنید. مجموع ضرایب باید دقیقاً ۱۰۰٪ باشد.',
        'jf_stage_name': 'نام مرحله',
        'jf_stage_type': 'نوع ارزیابی',
        'jf_stage_weight': 'ضریب (وزن) - ٪',
        'jf_stage_pass': 'حداقل نمره قبولی (از ۱۰۰)',
        'jf_stage_seq': 'ترتیب',
        'jf_add_stage': '➕ افزودن مرحله جدید',
        'jf_total_weight': 'مجموع ضرایب:',
        'jf_weight_error': 'توجه: مجموع ضرایب باید دقیقاً ۱۰۰٪ باشد.',

        # Job Pipeline
        'jp_title': 'پایپلاین ارزیابی:',
        'jp_back': 'بازگشت به فرصت‌های شغلی',
        'jp_sub': 'پایپلاین ارزیابی متقاضیان:',
        'jp_code': 'کد شغل:',
        'jp_dept': 'دپارتمان:',
        'jp_unit': 'واحد:',
        'jp_cat': 'رده شغلی:',
        'jp_print': 'چاپ و خروجی‌ها',
        'jp_doc_exam': 'سند آزمون استخدامی',
        'jp_doc_ad': 'آگهی استخدامی کاندیدا',
        'jp_doc_ap': 'Assessment Plan',
        'jp_doc_spec': 'سند مرکز آزمون',
        'jp_final_ranking': '🏆 رتبه‌بندی نهایی',
        'jp_total_candidates': 'تعداد متقاضیان:',
        'jp_stages_title': 'مراحل و ضرایب ارزیابی فرآیند',
        'jp_stage_completed': 'تکمیل شده',
        'jp_stage_weight': 'وزن مرحله:',
        'jp_all_completed_title': 'ارزیابی تمامی مراحل به پایان رسیده است!',
        'jp_all_completed_desc': 'تمام متقاضیان فعال در کلیه مراحل تعیین شده مورد ارزیابی قرار گرفته‌اند. اکنون می‌توانید برای رتبه‌بندی نهایی و تصمیم‌گیری نهایی اقدام نمایید.',
        'jp_all_completed_btn': '🏆 مشاهده رتبه‌بندی و تصمیم‌گیری نهایی',

        # Score Entry
        'se_title': 'ورود سریع نمرات آزمون و ارزیابی',
        'se_desc': 'فرصت شغلی مورد نظر را انتخاب کرده و نمرات و وضعیت مرحله جاری هر متقاضی را ثبت نمایید.',
        'se_search_job': '🔍 جستجوی فرصت شغلی (عنوان یا کد)',
        'se_search_placeholder': 'مثلاً: کارشناس، بازرس، ۴۱۲۰...',
        'se_search_btn': 'جستجو',
        'se_search_found': 'فرصت شغلی یافت شد برای',
        'se_select_job': 'انتخاب فرصت شغلی',
        'se_select_placeholder': '-- لطفاً یک فرصت شغلی را انتخاب کنید --',
        'se_loading': 'در حال بارگذاری...',
        'se_closed_warning': '⚠️ هشدار: این فرصت شغلی در وضعیت قرار دارد. امکان ثبت، ویرایش یا تغییر وضعیت متقاضیان در این وضعیت وجود ندارد.',
        'se_success': 'تغییرات نمرات و وضعیت‌های ارزیابی با موفقیت ثبت نهایی گردیدند.',
        'se_path': '🗺️ مسیر فرآیند استخدام:',
        'se_search_cand': 'جستجوی متقاضی (نام، نام خانوادگی، یا کد ملی):',
        'se_search_cand_placeholder': 'برای جستجو تایپ کنید...',
        'se_filter': 'فیلتر متقاضیان:',
        'se_filter_pending': 'فقط متقاضیان در حال بررسی (IN_PROGRESS)',
        'se_filter_completed': 'فقط تعیین تکلیف شده‌ها (نهایی)',
        'se_filter_all': 'همه متقاضیان فرصت شغلی',
        'se_show_failed': 'نمایش مردودین/ردشده‌ها',
        'se_bypass': 'ثبت آزاد (بای‌پس قفل‌ها)',
        'se_status_locked': '🔒 قفل شده (رد شده در مرحله قبل)',
        'se_no_stage': 'فاقد مرحله فعال',
        'se_score_lbl': 'نمره:',
        'se_status_lbl': 'وضعیت:',
        'se_date_lbl': 'تاریخ ارزیابی:',
        'se_evaluator_lbl': 'ارزیاب مسئول:',
        'se_pass': 'قبول',
        'se_fail': 'مردود',
        'se_no_show': 'عدم حضور',
        'se_ac_details': '🎯 جزئیات نمرات کانون ارزیابی',
        'se_int_details': '💬 پنل نمرات مصاحبه حضوری',
        'se_save_all': '💾 ثبت نهایی و ذخیره نمرات گروهی',
        'se_no_cands': 'هیچ متقاضی یافت نشد یا در این فیلتر وجود ندارد.',
        'se_no_evaluations': 'هیچ مرحله ارزیابی برای این شغل تعریف نشده است.',

        # Final Ranking
        'fr_title': 'رتبه‌بندی نهایی و تصمیم‌گیری نهایی متقاضیان',
        'fr_sub': 'فرصت شغلی:',
        'fr_back': 'بازگشت به پایپلاین ارزیابی',
        'fr_excel': 'خروجی اکسل رتبه‌بندی',
        'fr_total_candidates': 'کل متقاضیان',
        'fr_headcount': 'ظرفیت جذب',
        'fr_average_score': 'میانگین کل نمرات',
        'fr_assessing_count': 'در حال بررسی نهایی',
        'fr_rank': 'رتبه',
        'fr_weighted_score': 'امتیاز کل موزون',
        'fr_stages_breakdown': 'ریز نمرات مراحل',
        'fr_final_decision': 'تصمیم‌گیری نهایی',
        'fr_select_status': '-- انتخاب وضعیت نهایی --',
        'fr_status_inprogress': 'در حال ارزیابی',
        'fr_status_selected': 'قبول نهایی',
        'fr_status_reserve': 'لیست ذخیره',
        'fr_status_rejected': 'مردود شده',
        'fr_save_decisions': '💾 ثبت و نهایی‌سازی تصمیمات استخدام متقاضیان',
    },
    'ar': {
        'dashboard': 'لوحة القيادة',
        'jobs': 'فرص العمل',
        'workflows': 'نماذج عملية التوظيف',
        'candidates': 'المتقدمين',
        'candidates_by_stage': 'مراقبة المتقدمين حسب المراحل',
        'planning': 'تخطيط التوظيف',
        'analytics': 'لوحة التحليلات والتقارير',
        'competencies': 'الكفاءات',
        'competency_bank': 'الكفاءات كبنك',
        'competency_models': 'نماذج الكفاءة',
        'custom_competencies': 'الكفاءات اليدوية',
        'recruitment_patterns': 'أنماط التوظيف',
        'upload_excel': 'تحميل إكسل الكفاءات',
        'score_entry': 'تسجيل وإدخال الدرجات',
        'interviews_panel': 'لوحة المقابلات',
        'assessment_pdf': 'مركز التقييم (PDF)',
        'talent_bank': 'بنك المواهب',
        'settings': 'إعدادات النظام',
        'preferences': 'تخصيص المظهر',
        'import_records': 'استيراد السجلات (إكسل)',
        'rbac': 'إدارة المستخدمين (RBAC)',
        'backup': 'النسخ الاحتياطي والاستعادة',
        'data_integrity': 'مراقبة سلامة البيانات',
        'ai_settings': 'إعدادات الذكاء الاصطناعي',
        'org_settings': 'إعدادات المؤسسة',
        'audit_logs': 'سجلات التدقيق',
        'logout': 'خروج',
        'welcome': 'مرحباً بك',
        'system_title': 'نظام بيجو الذكي للتوظيف والتعيين',
        'sidebar_title': 'نظام بيجو',
        'written_spec': 'مواصفات الامتحان التحريري',
        'lang_label': 'اختر اللغة',
        
        # Dashboard Translations
        'workspace': 'لوحة العمل الإلكترونية',
        'dashboard_welcome': 'مرحباً {name} — نظرة عامة على حالة التوظيف',
        'print_pdf': '🖨️ طباعة لوحة القيادة / PDF',
        'active_opportunities': 'الفرص النشطة',
        'in_flow': 'جارية',
        'candidates_assessing': 'المتقدمين تحت التقييم',
        'active_status': 'نشط',
        'selected_candidates_kpi': 'المقبولين نهائياً',
        'hired_kpi': 'تم توظيفهم',
        'total_unique_candidates': 'إجمالي المتقدمين المميزين',
        'resume_bank_kpi': 'بنك السير الذاتية',
        'pipeline_title': 'تغييرات مراحل التوظيف (خط أنابيب التوظيف)',
        'pipeline_stage': 'المرحلة',
        'pipeline_candidates': 'المتقدمين',
        'pipeline_percentage': 'النسبة المئوية',
        'out_of_total_jobs': 'من إجمالي {total} فرصة عمل',
        'out_of_total_candidates': 'من إجمالي {total} متقدم',
        'history_btn': '🕒 سجل الأنشطة',
        'jobs_btn': '📋 فرص العمل',
        'enter_scores': '✏️ تسجيل الدرجات',
        
        # Job Management Page Translations
        'job_management_title': 'إدارة فرص العمل',
        'job_sub': 'تعريف فرص العمل الجديدة وضبط المراحل والأوزان الديناميكية لعملية تقييم المتقدمين',
        'export_excel': 'تصدير إكسل',
        'bulk_status': 'تغيير الحالة الجماعي',
        'add_job': 'إضافة فرصة عمل جديدة',
        'search_job': 'البحث عن فرصة عمل',
        'search_placeholder': 'العنوان أو الرمز أو رقم الطلب...',
        'department_label': 'القسم',
        'all_departments': 'جميع الأقسام',
        'unit_label': 'الوحدة التنظيمية',
        'all_units': 'جميع الوحدات',
        'status_label': 'الحالة',
        'all_statuses': 'جميع الحالات',
        'recruitment_type_label': 'نوع التوظيف',
        'all_types': 'جميع الأنواع',
        'category_label': 'الفئة الوظيفية',
        'all_categories': 'جميع الفئات',
        'source_label': 'مصدر الإنشاء',
        'all_sources': 'جميع المصادر',
        'apply_filters': 'تطبيق التصفية',
        'clear_filters': 'مسح التصفية',
        'code_th': 'الرمز / رقم الطلب',
        'title_th': 'مسمى الوظيفة',
        'dept_th': 'القسم / الوحدة',
        'date_th': 'تاريخ الاستلام',
        'headcount_th': 'القدرة الاستيعابية',
        'type_th': 'نوع التوظيف',
        'candidates_th': 'المتقدمين المسجلين',
        'stages_th': 'مراحل وأوزان التقييم (حسب العملية)',
        'status_th': 'الحالة',
        'actions_th': 'الإجراءات',
        'request_lbl': 'الطلب:',
        'persons': 'شخص',
        'options': 'خيارات',
        'pipeline': 'خط الأنابيب',
        'no_data': 'لا توجد بيانات متاحة.',
        'job_cat_legend': '👥 المتقدمين النشطين في مراحل التقييم',
        'avg_days_legend': '⏱️ متوسط أيام البقاء في كل مرحلة',
        'job_level_legend': '🎖️ المتقدمين النشطين حسب الفئة الوظيفية',
        'job_status_legend': '📊 وضعية فرص العمل',
        'job_dist_legend': '📂 التوزيع حسب الفئة الوظيفية',
        'cand_status_legend': '📈 حالة ملفات المتقدمين',
        'job_ass_int_legend': '🎯 فرص العمل في مرحلة التقييم والمقابلة',
        'view_all_jobs': 'عرض جميع الفرص ←',
        'no_active_jobs_err': 'لم يتم العثور على فرص عمل نشطة في مراحل التقييم/المقابلة.',
        'delayed_candidates_legend': '⚠️ المتقدمين خارج SLA (المتأخرين)',
        'sla_dashboard_btn': 'لوحة تأخيرات SLA ←',
        'warning_badge': 'تنبيه',
        'pass_badge': 'مقبول',

        # --- Phase 2 Additions ---
        'wf_add_new': 'إضافة نموذج جديد',
        'wf_name': 'اسم النموذج',
        'wf_description': 'وصف النموذج',
        'wf_default_stages': 'مراحل وأوزان التقييم الافتراضية',
        'wf_no_desc': 'لم يتم تسجيل وصف.',
        'wf_no_stages': 'بدون مراحل افتراضية',
        'wf_confirm_delete': 'هل أنت متأكد من حذف هذا النموذج؟',
        'wf_empty_list': 'لم يتم تعريف أي نموذج عملية في النظام.',
        'edit': 'تعديل',
        'delete': 'حذف',
        'cancel': 'إلغاء',
        'cand_mgmt': 'إدارة المتقدمين',
        'cand_mgmt_sub': 'عرض وتعديل وإدارة جميع ملفات المتقدمين في النظام',
        'talent_bank_adv': 'بنك الكفاءات المتقدم (Talent Pool)',
        'talent_bank_sub': 'إدارة وتصفية ذكية وتعيين المتقدمين مباشرة للفرص الوظيفية',
        'import_excel': 'استيراد من إكسل',
        'add_candidate': 'إضافة متقدم جديد',
        'kpi_total_talents': 'إجمالي المواهب في البنك',
        'kpi_higher_edu': 'نسبة الدراسات العليا (ماجستير ودكتوراه)',
        'kpi_avg_exp': 'متوسط سنوات الخبرة للمتقدمين',
        'years_exp': 'سنة',
        'search_candidate_placeholder': 'البحث بالاسم، الرقم القومي أو البريد الإلكتروني...',
        'search_btn': 'بحث',
        'adv_filters_btn': '➕ التصفية المتقدمة للتعليم، الخبرات والمهارات',
        'degree_label': 'المؤهل العلمي:',
        'degree_all': 'جميع المؤهلات',
        'degree_assoc': 'دبلوم',
        'degree_bach': 'بكالوريوس',
        'degree_master': 'ماجستير',
        'degree_phd': 'دكتوراه',
        'major_label': 'التخصص الدراسي:',
        'major_placeholder': 'مثال: هندسة الكمبيوتر',
        'skill_label': 'المهارة:',
        'skill_placeholder': 'مثال: Python',
        'min_exp_label': 'الحد الأدنى للخبرة (سنوات):',
        'min_exp_placeholder': 'مثال: ٣',
        'min_exam_score_label': 'الحد الأدنى لامتحان التحريري:',
        'min_exam_placeholder': 'مثال: ٧٥',
        'min_interview_score_label': 'الحد الأدنى للمقابلة الشخصية:',
        'min_interview_placeholder': 'مثال: ٨٠',
        'min_assessment_score_label': 'الحد الأدنى لمركز التقييم:',
        'min_assessment_placeholder': 'مثال: ٧٠',
        'applied_job_filter_label': 'تصفية حسب الوظيفة المتقدم لها:',
        'applied_job_placeholder': '-- اختر الفرصة الوظيفية --',
        'smart_recommendation_label': '🧠 ترشيح ذكي للمتقدمين المناسبين للوظيفة:',
        'smart_recommendation_placeholder': '-- اختر الوظيفة للتحليل وترتيب المطابقة --',
        'clear_filters_btn': 'مسح التصفية',
        'apply_adv_filters_btn': 'تطبيق التصفية المتقدمة',
        'cand_name_th': 'الاسم واللقب',
        'cand_national_id_th': 'الرقم القومي / الوظيفي',
        'cand_contact_th': 'معلومات الاتصال',
        'cand_active_apps_th': 'الطلبات النشطة',
        'cand_personnel_lbl': 'الموظفين:',
        'cand_exam_lbl': 'الامتحان:',
        'cand_interview_lbl': 'المقابلة:',
        'cand_assessment_lbl': 'التقييم:',
        'cand_apps_count': 'طلب',
        'cand_match_score': 'مطابقة',
        'assign_job_btn': '🔗 تعيين للوظيفة',
        'view_profile_btn': 'عرض الملف الشخصي',
        'cand_delete_confirm': 'هل أنت متأكد من حذف هذا المتقدم وجميع سجلاته؟',
        'cand_empty_list': 'لم يتم العثور على أي متقدم بالبيانات المدخلة.',
        'showing_candidates': 'عرض {start} إلى {end} من {total} متقدم',
        'modal_assign_title': 'تعيين المتقدم لفرصة عمل نشطة',
        'modal_assign_text': 'سيتم تعيين المتقدم {name} لفرصة العمل النشطة كطلب تعاون جديد.',
        'modal_assign_select_lbl': 'اختر فرصة العمل المطلوبة:',
        'modal_assign_select_placeholder': '-- اختر فرصة عمل نشطة --',
        'modal_assign_no_jobs': 'لا توجد فرص عمل نشطة في النظام حالياً.',
        'modal_assign_submit': 'تسجيل التعيين وبدء التقييم',
        'modal_import_title': 'استيراد جماعي للمتقدمين من إكسل',
        'modal_import_text': 'يمكنك تحميل ملف إكسل لاستيراد المتقدمين جماعياً. لضمان دقة البيانات، يرجى تحميل النموذج وتعبئته أولاً.',
        'modal_import_download_template': 'تحميل نموذج ملف إكسل',
        'modal_import_job_select_lbl': 'فرصة العمل المرتبطة (اختياري):',
        'modal_import_job_select_placeholder': '-- تسجيل في بنك المواهب العام (بدون تعيين وظيفة) --',
        'modal_import_file_lbl': 'اختر ملف إكسل (.xlsx):',
        'modal_import_submit': 'تحميل وتسجيل المتقدمين',
        'stage_track_title': 'متابعة المتقدمين حسب مراحل التقييم',
        'stage_track_sub': 'قائمة بجميع المتقدمين في عملية التقييم النشطة مع إمكانية الفرز ورصد المرحلة الحالية',
        'stage_track_breadcrumbs': 'تتبع المتقدمين بالمراحل',
        'back_to_dashboard': 'العودة للوحة القيادة',
        'export_excel_btn': 'تصدير إكسل (Excel)',
        'kpi_total_assessing': 'إجمالي تحت التقييم',
        'kpi_screening': 'غربلة أولية',
        'search_track_placeholder': 'البحث بالاسم، الرقم القومي، رمز الوظيفة...',
        'filter_stage_placeholder': '-- تصفية حسب مرحلة التقييم --',
        'filter_job_placeholder': '-- تصفية حسب فرصة العمل --',
        'filter_dept_placeholder': '-- تصفية حسب القسم --',
        'apply_btn': 'تطبيق',
        'table_th_stage': 'المرحلة الحالية للتقييم',
        'table_th_score': 'الدرجة الإجمالية',
        'table_th_last_activity': 'آخر نشاط',
        'start_process': 'بدء العملية',
        'empty_track_list': 'لم يتم العثور على أي متقدم يطابق المعايير المحددة.',
        'showing_track_candidates': 'عرض {start} إلى {end} من {total} متقدم تحت التقييم',
        'planning_title': 'تخطيط التوظيف وتقدير القدرة الاستيعابية',
        'planning_sub': 'إدارة تقويم التوظيف، ومراقبة التزامات SLA للمراحل، والتحقق من القدرة الشهرية للمقيمين',
        'planning_gantt_conflict': '🔍 مراقبة التزامن والتداخلات',
        'planning_calendar_btn': '📅 تقويم تخطيط التوظيف',
        'planning_excel_btn': '📥 تصدير خطط التوظيف',
        'planning_config_btn': '⚙️ إعدادات SLA والقدرات الاستيعابية',
        'kpi_active_plans': 'الخطط النشطة',
        'kpi_delayed_plans': 'خارج SLA (متأخر)',
        'kpi_draft_plans': 'مسودات الخطط',
        'kpi_today_jalali': 'تاريخ اليوم (هجري شمسى)',
        'planning_active_badge': 'نشط',
        'planning_delayed_badge': 'متأخر',
        'planning_draft_badge': 'مسودة',
        'planning_today_badge': 'اليوم',
        'planning_job_unit': 'فرصة عمل',
        'planning_plan_unit': 'خطة',
        'planning_capacity_monthly': 'متابعة قدرة مراحل التقييم لشهر ({month})',
        'planning_prev_month': '◀ الشهر السابق',
        'planning_next_month': 'الشهر التالي ▶',
        'planning_candidate_limit': '{consumed} / {limit} متقدم',
        'planning_remaining_capacity': 'القدرة المتبقية: <strong>{remaining} شخص</strong>',
        'planning_consumed_percentage': 'تم استهلاك {percentage}٪',
        'planning_agenda_title': '📅 جدول أعمال السبعة أيام القادمة',
        'planning_agenda_sub': 'بداية ونهاية مراحل التقييم بناءً على الخطط النشطة في الأسبوع القادم',
        'planning_agenda_excel': '📥 تصدير الجدول الأسبوعي',
        'planning_agenda_print': '🖨 طباعة / تصدير PDF الأسبوعي',
        'planning_agenda_start': 'بدء',
        'planning_agenda_end': 'انتهاء',
        'planning_agenda_stage_text': 'المرحلة <strong class="text-dark">{stage}</strong> للوظيفة <strong>{job}</strong>',
        'planning_no_agenda': 'لا توجد أحداث مجدولة للسبعة أيام القادمة.',
        'planning_unplanned_jobs_title': 'وظائف غير مجدولة',
        'planning_unplanned_jobs_sub': 'فرص العمل النشطة التي لم يتم تسجيل خطة زمنية لتوظيفها بعد.',
        'planning_unplanned_code_headcount': 'الرمز: {code} | العدد المطلوب: {headcount}',
        'planning_unplanned_btn': '📅 تخطيط وتجدول',
        'planning_all_planned_msg': 'تمت جدولة وتخطيط جميع فرص العمل النشطة.',
        'planning_active_plans_title': 'خطط التوظيف النشطة وتقويم العمليات',
        'planning_filter_active_badge': 'تصفية نشطة',
        'planning_search_placeholder': 'البحث بمسمى الوظيفة أو الرمز...',
        'planning_all_depts_placeholder': 'جميع الأقسام / الوحدات',
        'planning_sort_newest': 'الخطط الأحدث',
        'planning_sort_oldest': 'الخطط الأقدم',
        'planning_sort_start_asc': 'تاريخ بدء العملية (من الأقدم للأحدث)',
        'planning_sort_start_desc': 'تاريخ بدء العملية (من الأحدث للأقدم)',
        'planning_sort_end_asc': 'النهاية المتوقعة (تصاعدي)',
        'planning_sort_end_desc': 'النهاية المتوقعة (تنازلي)',
        'planning_sort_title': 'مسمى الوظيفة (أبجدي)',
        'planning_sort_headcount': 'العدد المطلوب (الأكثر)',
        'planning_filter_submit': 'تطبيق الفلتر',
        'planning_headcount_lbl': 'العدد المطلوب: <strong class="text-primary">{count} شخص</strong>',
        'planning_start_lbl': 'البدء: <strong>{date}</strong>',
        'planning_end_lbl': 'النهاية المتوقعة: <strong class="text-success">{date}</strong>',
        'planning_edit_btn': '📝 تعديل الجدولة',
        'planning_pipeline_btn': '📊 دخول لخط التقييم',
        'planning_empty_plans_msg': 'لا توجد خطط توظيف نشطة مسجلة في النظام.',
        'planning_empty_plans_sub': 'قم بجدولة فرص العمل من الجدول أعلى اليمين.',

        # --- Phase 3 Additions ---
        'cd_title': 'ملف المتقدم:',
        'cd_back': 'العودة لقائمة المتقدمين',
        'cd_sub': 'عرض كامل بيانات الهوية، التعليم، العمل وتاريخ التقييمات',
        'cd_new_app': 'تسجيل طلب جديد (تعيين للوظيفة)',
        'cd_print_resume': 'طباعة السيرة الذاتية',
        'cd_edit_candidate': 'تعديل بيانات المتقدم',
        'cd_national_id': 'الرقم القومي:',
        'cd_personnel_number': 'الرقم الوظيفي:',
        'cd_phone': 'رقم الاتصال',
        'cd_email': 'البريد الإلكتروني',
        'cd_created_at': 'تاريخ التسجيل بالنظام',
        'cd_download_resume': 'تحميل السيرة الذاتية',
        'cd_no_resume': 'لا توجد سيرة ذاتية مرفوعة',
        'cd_edu_title': 'المؤهلات الدراسية والتعليم',
        'cd_graduation': 'التخرج:',
        'cd_gpa': 'المعدل:',
        'cd_no_edu': 'لم يتم تسجيل مؤهلات دراسية.',
        'cd_exp_title': 'الخبرات المهنية وسوابق العمل',
        'cd_exp_range': 'الفترة:',
        'cd_now': 'حتى الآن',
        'cd_no_exp': 'لم يتم تسجيل خبرات سابقة.',
        'cd_skills_title': 'المهارات واللغات الأجنبية',
        'cd_skills_sub': 'المهارات الفنية والتخصصية',
        'cd_no_skill': 'لم يتم تسجيل مهارات.',
        'cd_langs_sub': 'اللغات الأجنبية',
        'cd_no_lang': 'لم يتم تسجيل لغات.',
        'cd_certs_title': 'الدورات التدريبية والشهادات',
        'cd_certs_date': 'الحصول عليها:',
        'cd_certs_exp': 'الانتهاء:',
        'cd_certs_no_exp': 'صلاحية دائمة',
        'cd_no_certs': 'لم يتم تسجيل شهادات أو دورات.',
        'cd_apps_title': 'سجل طلبات التوظيف والتعاون',
        'cd_apps_job': 'فرصة العمل',
        'cd_apps_date': 'تاريخ تقديم الطلب',
        'cd_apps_stage': 'المرحلة الحالية للتقييم',
        'cd_apps_score': 'الدرجة الإجمالية',
        'cd_apps_status': 'الحالة النهائية',
        'cd_apps_transcript': 'بيان درجات التقييم',
        'cd_no_apps': 'لا توجد طلبات مسجلة لهذا المتقدم حتى الآن.',

        'cf_edit_title': 'تعديل المتقدم:',
        'cf_add_title': 'إضافة متقدم جديد',
        'cf_edit_sub': 'تعديل ملف المتقدم:',
        'cf_add_sub': 'تسجيل متقدم جديد',
        'cf_desc': 'يرجى إدخال البيانات الشخصية، الدراسية وسجل الخبرات المهنية للمتقدم',
        'cf_errors': 'يرجى مراجعة وتصحيح الأخطاء الموجودة في النموذج.',
        'cf_section_general': '١. البيانات الشخصية والهوية',
        'cf_first_name': 'الاسم الأول',
        'cf_last_name': 'اسم العائلة',
        'cf_national_id': 'الرقم القومي',
        'cf_personnel': 'الرقم الوظيفي (للموظفين الداخليين)',
        'cf_phone': 'رقم الهاتف للاتصال',
        'cf_email': 'البريد الإلكتروني المعتمد',
        'cf_resume': 'ملف السيرة الذاتية (PDF أو Word)',
        'cf_current_file': 'الملف الحالي:',
        'cf_view_resume': 'عرض السيرة الذاتية الحالية',
        'cf_section_edu': '٢. المؤهلات التعليمية',
        'cf_add_edu': 'إضافة مؤهل دراسي',
        'cf_degree': 'المؤهل العلمي',
        'cf_major': 'التخصص الدراسي',
        'cf_univ': 'الجامعة / المعهد التعليمي',
        'cf_gpa': 'المعدل التراكمي',
        'cf_grad_year': 'سنة التخرج',
        'cf_delete_row': 'حذف السجل',
        'cf_section_exp': '٣. الخبرات المهنية وسوابق العمل',
        'cf_add_exp': 'إضافة خبرة سابقة',
        'cf_company': 'اسم الشركة / المؤسسة',
        'cf_job_title': 'المسمى الوظيفي',
        'cf_start_date': 'تاريخ البدء (هجري شمسي)',
        'cf_end_date': 'تاريخ الانتهاء (هجري شمسي)',
        'cf_exp_desc': 'تفاصيل المهام والمسؤوليات والإنجازات',
        'cf_save': 'حفظ التعديلات والبيانات',
        'cf_create': 'إنشاء وتسجيل المتقدم',

        'jf_edit_title': 'تعديل فرصة العمل',
        'jf_add_title': 'إضافة فرصة عمل جديدة',
        'jf_edit_sub': 'تعديل فرصة العمل:',
        'jf_desc': 'يرجى تحديد تفاصيل الوظيفة ومراحل وأوزان عملية التقييم للمتقدمين',
        'jf_section_general': '١. التفاصيل العامة لفرصة العمل',
        'jf_req_num': 'رقم الطلب الرسمي',
        'jf_code': 'رمز الوظيفة المميز',
        'jf_title': 'مسمى الوظيفة',
        'jf_dept': 'القسم / الإدارة المختصة',
        'jf_unit': 'الوحدة التنظيمية الفرعية',
        'jf_cat': 'الفئة والمستوى الوظيفي',
        'jf_headcount': 'العدد المطلوب لتوظيفه',
        'jf_type': 'نوع التوظيف والتعاقد',
        'jf_section_planning': '٢. التخطيط وجدولة التوظيف',
        'jf_recruiter': 'مسؤول التوظيف المعين للوظيفة',
        'jf_workflow': 'نموذج مسار التوظيف المعتمد (Workflow)',
        'jf_workflow_help': 'سيؤدي اختيار النموذج لتعبئة وتخصيص مراحل التقييم تلقائياً.',
        'jf_status': 'حالة فرصة العمل الحالية',
        'jf_start_date': 'تاريخ البدء المخطط',
        'jf_end_date': 'تاريخ الانتهاء المتوقع',
        'jf_section_competencies': '٣. الكفاءات الأساسية للتقييم',
        'jf_competencies_help': 'يرجى تحديد المهارات والكفاءات المطلوبة للوظيفة، حيث ستشكل أساس التقييم في مركز التقييم.',
        'jf_section_stages': '٤. إدارة مراحل وأوزان التقييم',
        'jf_stages_help': 'يرجى تحديد المراحل المطلوبة لتقييم المتقدمين والوزن النسبي لكل مرحلة، على أن يكون المجموع الإجمالي للأوزان ١٠٠٪ تماماً.',
        'jf_stage_name': 'مسمى المرحلة',
        'jf_stage_type': 'نوع مرحلة التقييم',
        'jf_stage_weight': 'الوزن النسبي (٪)',
        'jf_stage_pass': 'الحد الأدنى للنجاح (من ١٠٠)',
        'jf_stage_seq': 'الترتيب والتسلسل',
        'jf_add_stage': '➕ إضافة مرحلة تقييم جديدة',
        'jf_total_weight': 'مجموع الأوزان المحددة:',
        'jf_weight_error': 'تنبيه: يجب أن يكون مجموع الأوزان مساوياً لـ ١٠٠٪ تماماً.',

        'jp_title': 'مسار التقييم (خط الأنابيب):',
        'jp_back': 'العودة لفرص العمل',
        'jp_sub': 'مراحل تقييم المتقدمين للوظيفة:',
        'jp_code': 'رمز الوظيفة:',
        'jp_dept': 'القسم المختص:',
        'jp_unit': 'الوحدة الفرعية:',
        'jp_cat': 'الفئة الوظيفية:',
        'jp_print': 'طباعة وتصدير التقارير',
        'jp_doc_exam': 'نموذج الامتحان التحريري للتوظيف',
        'jp_doc_ad': 'إعلان الوظيفة للمتقدمين',
        'jp_doc_ap': 'خطة مركز التقييم (Assessment Plan)',
        'jp_doc_spec': 'دليل مركز الاختبارات والتقييم',
        'jp_final_ranking': '🏆 الترتيب والتصنيف النهائي للمرشحين',
        'jp_total_candidates': 'إجمالي المتقدمين للوظيفة:',
        'jp_stages_title': 'مراحل التقييم والوزن النسبي المعتمد',
        'jp_stage_completed': 'تم اكتمال التقييم',
        'jp_stage_weight': 'الوزن المعتمد للمرحلة:',
        'jp_all_completed_title': 'تمت مراجعة وتقييم جميع مراحل التوظيف بنجاح!',
        'jp_all_completed_desc': 'لقد أنهى المقيمون إدخال درجات كافة المتقدمين في جميع المراحل. يمكنك الآن الانتقال لمرحلة الترتيب والتوصية النهائية للاعتماد.',
        'jp_all_completed_btn': '🏆 الانتقال للترتيب والتوصية النهائية للاعتماد',

        'se_title': 'إدخال سريع لدرجات الاختبارات والتقييم',
        'se_desc': 'يرجى تحديد فرصة العمل لتسجيل درجات الاختبارات وحالة المرشحين في المرحلة الحالية مباشرة.',
        'se_search_job': '🔍 البحث السريع عن وظيفة (بالرمز أو المسمى)',
        'se_search_placeholder': 'مثال: مهندس، كاتب، ٤١٢٠...',
        'se_search_btn': 'بحث',
        'se_search_found': 'فرص العمل المطابقة لبحث',
        'se_select_job': 'اختر فرصة العمل المستهدفة',
        'se_select_placeholder': '-- يرجى اختيار فرصة عمل نشطة لتسجيل الدرجات --',
        'se_loading': 'جاري تحميل البيانات والمصفوفة...',
        'se_closed_warning': '⚠️ تنبيه: فرصة العمل الحالية مغلقة أو ملغاة في وضع «{status}». لا يمكن تسجيل أو تعديل درجات المرشحين.',
        'se_success': 'تم حفظ وتسجيل درجات وحالات التقييم بنجاح.',
        'se_path': '🗺️ مسار مراحل عملية التوظيف المعتمد:',
        'se_search_cand': 'البحث عن مرشح (الاسم، اللقب أو الرقم القومي):',
        'se_search_cand_placeholder': 'ابدأ بكتابة الاسم للبحث الفوري...',
        'se_filter': 'تصفية قائمة المرشحين:',
        'se_filter_pending': 'المرشحين في مرحلة المراجعة (تحت التقييم)',
        'se_filter_completed': 'المرشحين الذين تم حسم قرارهم (نهائي)',
        'se_filter_all': 'كافة المرشحين المتقدمين للوظيفة',
        'se_show_failed': 'عرض المرشحين المستبعدين/المردودين',
        'se_bypass': 'تسجيل حر ومستقل (تجاوز شروط وقفل التسلسل)',
        'se_status_locked': '🔒 مغلق (مستبعد في مرحلة سابقة)',
        'se_no_stage': 'لا توجد مرحلة تقييم نشطة حالياً',
        'se_score_lbl': 'الدرجة:',
        'se_status_lbl': 'القرار:',
        'se_date_lbl': 'تاريخ التقييم:',
        'se_evaluator_lbl': 'المقيم المسؤول:',
        'se_pass': 'اجتياز / قبول',
        'se_fail': 'استبعاد / مردود',
        'se_no_show': 'غياب / عدم حضور',
        'se_ac_details': '🎯 درجات وتفاصيل بنود مركز التقييم',
        'se_int_details': '💬 استمارة ودرجات المقابلة الشخصية',
        'se_save_all': '💾 حفظ وتسجيل كافة درجات المجموعة الحالية',
        'se_no_cands': 'لا يوجد مرشحون يطابقون خيارات التصفية الحالية.',
        'se_no_evaluations': 'لم يتم إعداد أو تخصيص مراحل تقييم لهذه الوظيفة.',

        'fr_title': 'الترتيب والتصنيف النهائي والاعتماد للمرشحين',
        'fr_sub': 'فرصة العمل المستهدفة:',
        'fr_back': 'العودة لمسار التقييم والخط',
        'fr_excel': 'تصدير كشف الترتيب لإكسل',
        'fr_total_candidates': 'إجمالي المتقدمين',
        'fr_headcount': 'العدد المستهدف للتوظيف',
        'fr_average_score': 'متوسط الدرجات الكلي',
        'fr_assessing_count': 'قيد المراجعة النهائية والاعتماد',
        'fr_rank': 'الترتيب',
        'fr_weighted_score': 'الدرجة الكلية الموزونة',
        'fr_stages_breakdown': 'تفصيل درجات المراحل المعتمدة',
        'fr_final_decision': 'القرار والتوصية النهائية',
        'fr_select_status': '-- حدد القرار النهائي للمرشح --',
        'fr_status_inprogress': 'تحت الدراسة والتقييم',
        'fr_status_selected': 'قبول نهائي للتعيين',
        'fr_status_reserve': 'إدراج بقائمة الاحتياط',
        'fr_status_rejected': 'مستبعد / عدم قبول',
        'fr_save_decisions': '💾 اعتماد وتثبيت قرارات التوظيف لكافة المرشحين المحددين',
    },
    'en': {
        'dashboard': 'Dashboard',
        'jobs': 'Job Opportunities',
        'workflows': 'Recruitment Workflows',
        'candidates': 'Candidates',
        'candidates_by_stage': 'Track Candidates by Stage',
        'planning': 'Recruitment Planning',
        'analytics': 'Analytics & Reports',
        'competencies': 'Competencies',
        'competency_bank': 'Competency Bank',
        'competency_models': 'Competency Models',
        'custom_competencies': 'Custom Competencies',
        'recruitment_patterns': 'Recruitment Patterns',
        'upload_excel': 'Upload Competency Excel',
        'score_entry': 'Enter Scores',
        'interviews_panel': 'Interviews Panel',
        'assessment_pdf': 'Assessment Center (PDF)',
        'talent_bank': 'Talent Bank',
        'settings': 'System Settings',
        'preferences': 'Appearance Settings',
        'import_records': 'Import Excel Records',
        'rbac': 'User Management (RBAC)',
        'backup': 'Backup & Restore',
        'data_integrity': 'Data Integrity Monitor',
        'ai_settings': 'AI Settings',
        'org_settings': 'Organization Settings',
        'audit_logs': 'Audit Logs',
        'logout': 'Logout',
        'welcome': 'Welcome',
        'system_title': 'Recruitment System',
        'sidebar_title': 'Recruitment System',
        'written_spec': 'Written Exam Spec',
        'lang_label': 'Language',
        
        # Dashboard Translations
        'workspace': 'Electronic Workspace',
        'dashboard_welcome': 'Hello {name} — Real-time view of recruitment',
        'print_pdf': '🖨️ Print Dashboard / PDF',
        'active_opportunities': 'Active Opportunities',
        'in_flow': 'In Progress',
        'candidates_assessing': 'Candidates in Assessment',
        'active_status': 'Active',
        'selected_candidates_kpi': 'Selected Candidates',
        'hired_kpi': 'Hired',
        'total_unique_candidates': 'Total Unique Candidates',
        'resume_bank_kpi': 'Resume Bank',
        'pipeline_title': 'Recruitment Pipeline & Phase Changes',
        'pipeline_stage': 'Stage',
        'pipeline_candidates': 'Candidates',
        'pipeline_percentage': 'Percentage',
        'out_of_total_jobs': 'out of {total} total job posts',
        'out_of_total_candidates': 'out of {total} total candidates',
        'history_btn': '🕒 Activity History',
        'jobs_btn': '📋 Job Opportunities',
        'enter_scores': '✏️ Enter Scores',
        
        # Job Management Page Translations
        'job_management_title': 'Job Opportunities Management',
        'job_sub': 'Define new job opportunities and configure dynamic stages/weights for candidate evaluation',
        'export_excel': 'Export Excel',
        'bulk_status': 'Bulk Status Change',
        'add_job': 'Add New Job Opportunity',
        'search_job': 'Search Job Opportunity',
        'search_placeholder': 'Title, job code or request number...',
        'department_label': 'Department',
        'all_departments': 'All Departments',
        'unit_label': 'Organizational Unit',
        'all_units': 'All Units',
        'status_label': 'Status',
        'all_statuses': 'All Statuses',
        'recruitment_type_label': 'Employment Type',
        'all_types': 'All Types',
        'category_label': 'Job Category',
        'all_categories': 'All Categories',
        'source_label': 'Creation Source',
        'all_sources': 'All Sources',
        'apply_filters': 'Apply Filters',
        'clear_filters': 'Clear',
        'code_th': 'Code / Request No',
        'title_th': 'Job Title',
        'dept_th': 'Department / Unit',
        'date_th': 'Date Received',
        'headcount_th': 'Headcount',
        'type_th': 'Employment Type',
        'candidates_th': 'Registered Candidates',
        'stages_th': 'Assessment Stages & Weights (in order)',
        'status_th': 'Status',
        'actions_th': 'Actions',
        'request_lbl': 'Request:',
        'persons': 'person(s)',
        'options': 'Options',
        'pipeline': 'Pipeline',
        'no_data': 'No data available.',
        'job_cat_legend': '👥 Active Candidates in Assessment Stages',
        'avg_days_legend': '⏱️ Avg Days Spent in Each Stage',
        'job_level_legend': '🎖️ Active Candidates by Job Level',
        'job_status_legend': '📊 Job Opportunities Status',
        'job_dist_legend': '📂 Distribution by Job Category',
        'cand_status_legend': '📈 Candidate Application Status',
        'job_ass_int_legend': '🎯 Jobs in Assessment/Interview Stages',
        'view_all_jobs': 'View All Jobs ←',
        'no_active_jobs_err': 'No active jobs found in Assessment/Interview stages.',
        'delayed_candidates_legend': '⚠️ Delayed Candidates (Out of SLA)',
        'sla_dashboard_btn': 'SLA Delays Dashboard ←',
        'warning_badge': 'Warning',
        'pass_badge': 'Pass',

        # --- Phase 2 Additions ---
        'wf_add_new': 'Add New Template',
        'wf_name': 'Template Name',
        'wf_description': 'Description',
        'wf_default_stages': 'Default Evaluation Stages & Weights',
        'wf_no_desc': 'No description provided.',
        'wf_no_stages': 'No default stages',
        'wf_confirm_delete': 'Are you sure you want to delete this process template?',
        'wf_empty_list': 'No process templates defined in the system.',
        'edit': 'Edit',
        'delete': 'Delete',
        'cancel': 'Cancel',
        'cand_mgmt': 'Candidates Management',
        'cand_mgmt_sub': 'View, edit, and manage all candidate profiles in the system',
        'talent_bank_adv': 'Advanced Talent Pool',
        'talent_bank_sub': 'Manage, filter smart, and assign candidates directly to job opportunities',
        'import_excel': 'Import Excel',
        'add_candidate': 'Add New Candidate',
        'kpi_total_talents': 'Total Talents in Pool',
        'kpi_higher_edu': 'Higher Education Share (Master/PhD)',
        'kpi_avg_exp': 'Average Candidate Experience',
        'years_exp': 'year(s)',
        'search_candidate_placeholder': 'Search by name, surname, national ID or email...',
        'search_btn': 'Search',
        'adv_filters_btn': '➕ Advanced Education, Experience & Skills Filters',
        'degree_label': 'Education Degree:',
        'degree_all': 'All Degrees',
        'degree_assoc': 'Associate Degree',
        'degree_bach': 'Bachelor\'s Degree',
        'degree_master': 'Master\'s Degree',
        'degree_phd': 'PhD / Doctorate',
        'major_label': 'Major / Field of Study:',
        'major_placeholder': 'e.g., Computer Engineering',
        'skill_label': 'Skill:',
        'skill_placeholder': 'e.g., Python',
        'min_exp_label': 'Min Experience (Years):',
        'min_exp_placeholder': 'e.g., 3',
        'min_exam_score_label': 'Min Written Exam Score:',
        'min_exam_placeholder': 'e.g., 75',
        'min_interview_score_label': 'Min Interview Score:',
        'min_interview_placeholder': 'e.g., 80',
        'min_assessment_score_label': 'Min Assessment Center Score:',
        'min_assessment_placeholder': 'e.g., 70',
        'applied_job_filter_label': 'Filter by Applied Job Opportunity:',
        'applied_job_placeholder': '-- Select Job Opportunity --',
        'smart_recommendation_label': '🧠 AI Fit Recommendations for Job:',
        'smart_recommendation_placeholder': '-- Select Job for AI Match Analysis & Ranking --',
        'clear_filters_btn': 'Clear Filters',
        'apply_adv_filters_btn': 'Apply Advanced Filters',
        'cand_name_th': 'Candidate Name',
        'cand_national_id_th': 'National / Personnel ID',
        'cand_contact_th': 'Contact Information',
        'cand_active_apps_th': 'Active Applications',
        'cand_personnel_lbl': 'Personnel ID:',
        'cand_exam_lbl': 'Exam:',
        'cand_interview_lbl': 'Interview:',
        'cand_assessment_lbl': 'Assessment:',
        'cand_apps_count': 'app(s)',
        'cand_match_score': 'match',
        'assign_job_btn': '🔗 Assign to Job',
        'view_profile_btn': 'View Profile',
        'cand_delete_confirm': 'Are you sure you want to delete this candidate and all of their applications?',
        'cand_empty_list': 'No candidates found matching the query.',
        'showing_candidates': 'Showing {start} to {end} of {total} candidates',
        'modal_assign_title': 'Assign Candidate to Active Job Post',
        'modal_assign_text': 'Assigning candidate {name} to an active job post will create a job application.',
        'modal_assign_select_lbl': 'Select Job Opportunity:',
        'modal_assign_select_placeholder': '-- Select Active Job Post --',
        'modal_assign_no_jobs': 'No active jobs available in the system.',
        'modal_assign_submit': 'Submit & Start Assessment',
        'modal_import_title': 'Bulk Candidate Import from Excel',
        'modal_import_text': 'You can import candidates in bulk by uploading an Excel sheet. To ensure data format, please download the template first.',
        'modal_import_download_template': 'Download Excel Template / Pattern',
        'modal_import_job_select_lbl': 'Assign to Job (Optional):',
        'modal_import_job_select_placeholder': '-- Save in General Talent Pool (No Job Assignment) --',
        'modal_import_file_lbl': 'Select Excel File (.xlsx):',
        'modal_import_submit': 'Upload & Register Candidates',
        'stage_track_title': 'Track Candidates by Assessment Stage',
        'stage_track_sub': 'List of all active candidates with options to monitor current assessment stages',
        'stage_track_breadcrumbs': 'Track Candidates by Stage',
        'back_to_dashboard': 'Back to Dashboard',
        'export_excel_btn': 'Export Excel',
        'kpi_total_assessing': 'Total Assessing',
        'kpi_screening': 'Screening',
        'search_track_placeholder': 'Search by name, national ID, job code...',
        'filter_stage_placeholder': '-- Filter by Stage --',
        'filter_job_placeholder': '-- Filter by Job Opportunity --',
        'filter_dept_placeholder': '-- Filter by Department --',
        'apply_btn': 'Apply',
        'table_th_stage': 'Current Stage',
        'table_th_score': 'Final Score',
        'table_th_last_activity': 'Last Activity',
        'start_process': 'Start Process',
        'empty_track_list': 'No candidates found in assessment matching the filter.',
        'showing_track_candidates': 'Showing {start} to {end} of {total} candidates in assessment',
        'planning_title': 'Recruitment Planning & Capacity Gauges',
        'planning_sub': 'Manage recruitment calendar, check stage SLA compliance, and monitor monthly assessor capacity',
        'planning_gantt_conflict': '🔍 Monitor Concurrency & Conflicts',
        'planning_calendar_btn': '📅 Recruitment Planning Calendar',
        'planning_excel_btn': '📥 Export Plans to Excel',
        'planning_config_btn': '⚙️ Configure SLA & Capacities',
        'kpi_active_plans': 'Active Plans',
        'kpi_delayed_plans': 'Out of SLA (Delayed)',
        'kpi_draft_plans': 'Draft Plans',
        'kpi_today_jalali': 'Today\'s Date (Shamsi)',
        'planning_active_badge': 'ACTIVE',
        'planning_delayed_badge': 'DELAYED',
        'planning_draft_badge': 'DRAFT',
        'planning_today_badge': 'TODAY',
        'planning_job_unit': 'job(s)',
        'planning_plan_unit': 'plan(s)',
        'planning_capacity_monthly': 'Monthly Assessment Stage Capacity ({month})',
        'planning_prev_month': '◀ Previous Month',
        'planning_next_month': 'Next Month ▶',
        'planning_candidate_limit': '{consumed} / {limit} candidates',
        'planning_remaining_capacity': 'Remaining Capacity: <strong>{remaining} person(s)</strong>',
        'planning_consumed_percentage': '{percentage}% consumed',
        'planning_agenda_title': '📅 Agenda for Next 7 Days',
        'planning_agenda_sub': 'Start and end dates of assessment stages scheduled in the upcoming week',
        'planning_agenda_excel': '📥 Export Weekly Agenda',
        'planning_agenda_print': '🖨 Print / PDF Weekly Agenda',
        'planning_agenda_start': 'START',
        'planning_agenda_end': 'END',
        'planning_agenda_stage_text': 'Stage <strong class="text-dark">{stage}</strong> for job <strong>{job}</strong>',
        'planning_no_agenda': 'No events scheduled for the next 7 days.',
        'planning_unplanned_jobs_title': 'Unplanned Jobs',
        'planning_unplanned_jobs_sub': 'Active job opportunities that do not have a schedule plan recorded yet.',
        'planning_unplanned_code_headcount': 'Code: {code} | Target headcount: {headcount}',
        'planning_unplanned_btn': '📅 Plan Job Schedule',
        'planning_all_planned_msg': 'All active job opportunities are planned.',
        'planning_active_plans_title': 'Active Recruitment Plans & Visual Timeline',
        'planning_filter_active_badge': 'Filter Active',
        'planning_search_placeholder': 'Search job title or code...',
        'planning_all_depts_placeholder': 'All Departments / Units',
        'planning_sort_newest': 'Newest Plans First',
        'planning_sort_oldest': 'Oldest Plans First',
        'planning_sort_start_asc': 'Start Date (Oldest to Newest)',
        'planning_sort_start_desc': 'Start Date (Newest to Oldest)',
        'planning_sort_end_asc': 'Predicted End Date (Ascending)',
        'planning_sort_end_desc': 'Predicted End Date (Descending)',
        'planning_sort_title': 'Job Title (Alphabetical)',
        'planning_sort_headcount': 'Target Headcount (Highest)',
        'planning_filter_submit': 'Apply Filter',
        'planning_headcount_lbl': 'Target Headcount: <strong class="text-primary">{count} person(s)</strong>',
        'planning_start_lbl': 'Start: <strong>{date}</strong>',
        'planning_end_lbl': 'Predicted End: <strong class="text-success">{date}</strong>',
        'planning_edit_btn': '📝 Edit Schedule',
        'planning_pipeline_btn': '📊 Go to Assessment Pipeline',
        'planning_empty_plans_msg': 'No active recruitment schedule plans found in the system.',
        'planning_empty_plans_sub': 'Plan job schedules from the table on the top right.',

        # --- Phase 3 Additions ---
        'cd_title': 'Candidate Profile:',
        'cd_back': 'Back to Candidate List',
        'cd_sub': 'Displaying complete profile, education, employment records and assessment history',
        'cd_new_app': 'Register New Request (Assign to Job)',
        'cd_print_resume': 'Print Resume',
        'cd_edit_candidate': 'Edit Candidate',
        'cd_national_id': 'National ID:',
        'cd_personnel_number': 'Personnel ID:',
        'cd_phone': 'Phone Number',
        'cd_email': 'Email Address',
        'cd_created_at': 'Registration Date',
        'cd_download_resume': 'Download Resume File',
        'cd_no_resume': 'No resume file uploaded',
        'cd_edu_title': 'Education History',
        'cd_graduation': 'Graduation:',
        'cd_gpa': 'GPA:',
        'cd_no_edu': 'No education records registered.',
        'cd_exp_title': 'Work Experience',
        'cd_exp_range': 'Period:',
        'cd_now': 'Present',
        'cd_no_exp': 'No work experience records registered.',
        'cd_skills_title': 'Skills & Languages',
        'cd_skills_sub': 'Technical Skills',
        'cd_no_skill': 'No skills registered.',
        'cd_langs_sub': 'Foreign Languages',
        'cd_no_lang': 'No foreign languages registered.',
        'cd_certs_title': 'Courses & Certificates',
        'cd_certs_date': 'Issued:',
        'cd_certs_exp': 'Expires:',
        'cd_certs_no_exp': 'No Expiration Date',
        'cd_no_certs': 'No certificates registered.',
        'cd_apps_title': 'Job Application History',
        'cd_apps_job': 'Job Opportunity',
        'cd_apps_date': 'Application Date',
        'cd_apps_stage': 'Current Stage',
        'cd_apps_score': 'Total Score',
        'cd_apps_status': 'Overall Status',
        'cd_apps_transcript': 'Assessment Transcript',
        'cd_no_apps': 'No applications registered for this candidate yet.',

        'cf_edit_title': 'Edit Candidate:',
        'cf_add_title': 'Add New Candidate',
        'cf_edit_sub': 'Edit Candidate File:',
        'cf_add_sub': 'Register New Candidate',
        'cf_desc': 'Enter candidate\'s personal identity, education, and work experience',
        'cf_errors': 'Please check and fix the errors in the form.',
        'cf_section_general': '1. General & Identity Information',
        'cf_first_name': 'First Name',
        'cf_last_name': 'Last Name',
        'cf_national_id': 'National ID',
        'cf_personnel': 'Personnel Number (for internal staff)',
        'cf_phone': 'Phone Number',
        'cf_email': 'Email Address',
        'cf_resume': 'Resume File (PDF or Word)',
        'cf_current_file': 'Current File:',
        'cf_view_resume': 'View Current Resume',
        'cf_section_edu': '2. Education History',
        'cf_add_edu': 'Add Education Record',
        'cf_degree': 'Degree Level',
        'cf_major': 'Major / Field',
        'cf_univ': 'University / Institute',
        'cf_gpa': 'GPA',
        'cf_grad_year': 'Graduation Year',
        'cf_delete_row': 'Remove Record',
        'cf_section_exp': '3. Work Experience',
        'cf_add_exp': 'Add Work Experience',
        'cf_company': 'Company / Organization Name',
        'cf_job_title': 'Job Title',
        'cf_start_date': 'Start Date (Shamsi)',
        'cf_end_date': 'End Date (Shamsi)',
        'cf_exp_desc': 'Description & Achievements',
        'cf_save': 'Save Changes',
        'cf_create': 'Create Candidate',

        'jf_edit_title': 'Edit Job Opportunity',
        'jf_add_title': 'Add New Job Opportunity',
        'jf_edit_sub': 'Edit Job Opportunity:',
        'jf_desc': 'Configure job opportunity details and stages of candidate assessment',
        'jf_section_general': '1. General Job Information',
        'jf_req_num': 'Request Number',
        'jf_code': 'Job Code',
        'jf_title': 'Job Title',
        'jf_dept': 'Department',
        'jf_unit': 'Organizational Unit',
        'jf_cat': 'Job Level/Category',
        'jf_headcount': 'Target Headcount',
        'jf_type': 'Employment Type',
        'jf_section_planning': '2. Planning & Schedule',
        'jf_recruiter': 'Assigned Recruiter',
        'jf_workflow': 'Recruitment Process Template (Workflow)',
        'jf_workflow_help': 'Selecting a template will auto-fill evaluation stages.',
        'jf_status': 'Job Post Status',
        'jf_start_date': 'Start Date',
        'jf_end_date': 'End Date',
        'jf_section_competencies': '3. Competencies to Evaluate',
        'jf_competencies_help': 'Select key competencies required for this job. These will form the base of evaluations at the assessment center.',
        'jf_section_stages': '4. Manage Assessment Stages & Weights',
        'jf_stages_help': 'Specify stages and weights for evaluating candidates. The total sum of weights must equal exactly 100%.',
        'jf_stage_name': 'Stage Name',
        'jf_stage_type': 'Evaluation Type',
        'jf_stage_weight': 'Weight (٪)',
        'jf_stage_pass': 'Minimum Passing Score (out of 100)',
        'jf_stage_seq': 'Sequence',
        'jf_add_stage': '➕ Add New Stage',
        'jf_total_weight': 'Total Weight:',
        'jf_weight_error': 'Warning: Sum of weights must equal exactly 100%.',

        'jp_title': 'Evaluation Pipeline:',
        'jp_back': 'Back to Jobs',
        'jp_sub': 'Candidate evaluation stages:',
        'jp_code': 'Job Code:',
        'jp_dept': 'Department:',
        'jp_unit': 'Unit:',
        'jp_cat': 'Job Category:',
        'jp_print': 'Print & Export Documents',
        'jp_doc_exam': 'Written Exam Document',
        'jp_doc_ad': 'Job Advertisement Document',
        'jp_doc_ap': 'Assessment Plan Document',
        'jp_doc_spec': 'Exam Center Specifications',
        'jp_final_ranking': '🏆 Final Candidate Ranking',
        'jp_total_candidates': 'Total Candidates Registered:',
        'jp_stages_title': 'Evaluation Stages & Weights',
        'jp_stage_completed': 'Evaluation Completed',
        'jp_stage_weight': 'Stage Weight:',
        'jp_all_completed_title': 'All stages evaluation are completed!',
        'jp_all_completed_desc': 'All active candidates in all defined stages have been evaluated. You can now view final rankings and make decisions.',
        'jp_all_completed_btn': '🏆 View Final Rankings & Decision Making',

        'se_title': 'Quick Score and Assessment Entry',
        'se_desc': 'Select job opportunity and record evaluation scores and status directly in the current stage.',
        'se_search_job': '🔍 Search Job Post (by Code or Title)',
        'se_search_placeholder': 'e.g. Engineer, Auditor, 4120...',
        'se_search_btn': 'Search',
        'se_search_found': 'matching job posts found for',
        'se_select_job': 'Select Job Opportunity',
        'se_select_placeholder': '-- Please select a job opportunity to enter scores --',
        'se_loading': 'Loading assessment matrix...',
        'se_closed_warning': '⚠️ Warning: This job opportunity is currently Closed/Cancelled in state "{status}". No changes allowed.',
        'se_success': 'Assessment scores and statuses have been successfully submitted.',
        'se_path': '🗺️ Recruitment Process Path:',
        'se_search_cand': 'Search candidate (by Name, Surname, or National ID):',
        'se_search_cand_placeholder': 'Start typing name to search...',
        'se_filter': 'Filter candidates:',
        'se_filter_pending': 'Only candidates under review (IN_PROGRESS)',
        'se_filter_completed': 'Only finalized decisions (Completed)',
        'se_filter_all': 'All candidates of this job',
        'se_show_failed': 'Show failed / rejected candidates',
        'se_bypass': 'Free score entry (Bypass sequence locks)',
        'se_status_locked': '🔒 Locked (Rejected in previous stage)',
        'se_no_stage': 'No active stage',
        'se_score_lbl': 'Score:',
        'se_status_lbl': 'Status:',
        'se_date_lbl': 'Evaluation Date:',
        'se_evaluator_lbl': 'Assigned Evaluator:',
        'se_pass': 'PASS',
        'se_fail': 'FAIL',
        'se_no_show': 'NO SHOW',
        'se_ac_details': '🎯 Assessment Center Score Sheet',
        'se_int_details': '💬 Interview Score Panel',
        'se_save_all': '💾 Save and Submit All Scores',
        'se_no_cands': 'No candidates match the selected filters.',
        'se_no_evaluations': 'No evaluation stages defined for this job.',

        'fr_title': 'Final Candidate Ranking & Selection Decisions',
        'fr_sub': 'Target Job Opportunity:',
        'fr_back': 'Back to Evaluation Pipeline',
        'fr_excel': 'Export Ranking to Excel',
        'fr_total_candidates': 'Total Candidates',
        'fr_headcount': 'Target Headcount',
        'fr_average_score': 'Average Total Score',
        'fr_assessing_count': 'Final Decisions Pending',
        'fr_rank': 'Rank',
        'fr_weighted_score': 'Weighted Total Score',
        'fr_stages_breakdown': 'Evaluation Stage Scores',
        'fr_final_decision': 'Final Selection Decision',
        'fr_select_status': '-- Select Final Decision --',
        'fr_status_inprogress': 'Under Final Review',
        'fr_status_selected': 'Selected (Accepted)',
        'fr_status_reserve': 'Reserve List',
        'fr_status_rejected': 'Rejected',
        'fr_save_decisions': '💾 Register and Finalize Selection Decisions for All Candidates',
    },
    'tr': {
        'dashboard': 'Kontrol Paneli',
        'jobs': 'İş Fırsatları',
        'workflows': 'İşe Alım İş Akışları',
        'candidates': 'Adaylar',
        'candidates_by_stage': 'Aday Takip Aşamaları',
        'planning': 'İşe Alım Planlaması',
        'analytics': 'Analiz ve Raporlar',
        'competencies': 'Yetkinlikler',
        'competency_bank': 'Yetkinlik Havuzu',
        'competency_models': 'Yetkinlik Modelleri',
        'custom_competencies': 'Özel Yetkinlikler',
        'recruitment_patterns': 'İşe Alım Şablonları',
        'upload_excel': 'Yetkinlik Yükle (Excel)',
        'score_entry': 'Puan Girişi',
        'interviews_panel': 'Mülakat Paneli',
        'assessment_pdf': 'Değerlendirme Merkezi (PDF)',
        'talent_bank': 'Yetenek Havuzu',
        'settings': 'Sistem Ayarları',
        'preferences': 'Görünüm Ayarları',
        'import_records': 'Excel Veri İçe Aktar',
        'rbac': 'Kullanıcı Yönetimi (RBAC)',
        'backup': 'Yedekle & Geri Yükle',
        'data_integrity': 'Veri Tutarlılığı Monitörü',
        'ai_settings': 'Yapay Zeka Ayarları',
        'org_settings': 'Kurum Ayarları',
        'audit_logs': 'Denetim Günlükleri',
        'logout': 'Çıkış Yap',
        'welcome': 'Hoş geldiniz',
        'system_title': 'İşe Alım Sistemi',
        'sidebar_title': 'İşe Alım Sistemi',
        'written_spec': 'Yazılı Sınav Özellikleri',
        'lang_label': 'Dil Seçimi',
        
        # Dashboard Translations
        'workspace': 'Elektronik Çalışma Alanı',
        'dashboard_welcome': 'Merhaba {name} — İşe alım sürecinin anlık görünümü',
        'print_pdf': '🖨️ Paneli Yazdır / PDF',
        'active_opportunities': 'Aktif Fırsatlar',
        'in_flow': 'Devam Eden',
        'candidates_assessing': 'Değerlendirmedeki Adaylar',
        'active_status': 'Aktif',
        'selected_candidates_kpi': 'Kabul Edilen Adaylar',
        'hired_kpi': 'İşe Alınan',
        'total_unique_candidates': 'Toplam Tekil Adaylar',
        'resume_bank_kpi': 'Özgeçmiş Bankası',
        'pipeline_title': 'İşe Alım Aşamaları & Değişiklikler',
        'pipeline_stage': 'Aşama',
        'pipeline_candidates': 'Adaylar',
        'pipeline_percentage': 'Yüzde',
        'out_of_total_jobs': 'toplam {total} iş fırsatı arasından',
        'out_of_total_candidates': 'toplam {total} aday arasından',
        'history_btn': '🕒 Aktivite Geçmişi',
        'jobs_btn': '📋 İş Fırsatları',
        'enter_scores': '✏️ Puan Girişi',
        
        # Job Management Page Translations
        'job_management_title': 'İş Fırsatları Yönetimi',
        'job_sub': 'Yeni iş fırsatlarını tanımlayın ve aday değerlendirme süreçleri için dinamik aşamaları/ağırlıkları yapılandırın',
        'export_excel': 'Excel Çıktısı',
        'bulk_status': 'Toplu Durum Değişikliği',
        'add_job': 'Yeni İş Fırsatı Ekle',
        'search_job': 'İş Fırsatı Ara',
        'search_placeholder': 'Başlık, iş kodu veya talep numarası...',
        'department_label': 'Departman',
        'all_departments': 'Tüm Departmanlar',
        'unit_label': 'Organizasyonel Birim',
        'all_units': 'Tüm Birimler',
        'status_label': 'Durum',
        'all_statuses': 'Tüm Durumlar',
        'recruitment_type_label': 'İstihdam Türü',
        'all_types': 'Tüm Türler',
        'category_label': 'İş Kategorisi',
        'all_categories': 'Tüm Kategoriler',
        'source_label': 'Oluşturma Kaynağı',
        'all_sources': 'Tüm Kaynaklar',
        'apply_filters': 'Filtreleri Uygula',
        'clear_filters': 'Temizle',
        'code_th': 'Kod / Talep No',
        'title_th': 'İş Unvanı',
        'dept_th': 'Departman / Birim',
        'date_th': 'Alınma Tarihi',
        'headcount_th': 'Kontenjan',
        'type_th': 'İstihdam Türü',
        'candidates_th': 'Kayıtlı Adaylar',
        'stages_th': 'Değerlendirme Aşamaları & Ağırlıkları (sırasıyla)',
        'status_th': 'Durum',
        'actions_th': 'İşlemler',
        'request_lbl': 'Talep:',
        'persons': 'kişi',
        'options': 'Seçenekler',
        'pipeline': 'Aşamalar',
        'no_data': 'Kayıt bulunamadı.',
        'job_cat_legend': '👥 Değerlendirme Aşamalarındaki Aktif Adaylar',
        'avg_days_legend': '⏱️ Aşamada Geçirilen Ortalama Gün',
        'job_level_legend': '🎖️ Görev Derecesine Göre Aktif Adaylar',
        'job_status_legend': '📊 İş Fırsatları Durumu',
        'job_dist_legend': '📂 Görev Derecelerine Göre Dağılım',
        'cand_status_legend': '📈 Aday Başvuru Durumları',
        'job_ass_int_legend': '🎯 Değerlendirme/Mülakat Aşamasındaki İşler',
        'view_all_jobs': 'Tüm Fırsatları Gör ←',
        'no_active_jobs_err': 'Değerlendirme/Mülakat aşamasında aktif iş fırsatı bulunamadı.',
        'delayed_candidates_legend': '⚠️ SLA Dışı Geciken Adaylar',
        'sla_dashboard_btn': 'SLA Gecikmeleri Paneli ←',
        'warning_badge': 'Uyarı',
        'pass_badge': 'Geçti',

        # --- Phase 2 Additions ---
        'wf_add_new': 'Yeni Şablon Ekle',
        'wf_name': 'Şablon Adı',
        'wf_description': 'Açıklama',
        'wf_default_stages': 'Varsayılan Değerlendirme Aşamaları & Ağırlıkları',
        'wf_no_desc': 'Açıklama girilmemiş.',
        'wf_no_stages': 'Varsayılan aşama yok',
        'wf_confirm_delete': 'Bu iş akışı şablonunu silmek istediğinizden emin misiniz?',
        'wf_empty_list': 'Sistemde tanımlanmış iş akışı şablonu yok.',
        'edit': 'Düzenle',
        'delete': 'Sil',
        'cancel': 'İptal',
        'cand_mgmt': 'Aday Yönetimi',
        'cand_mgmt_sub': 'Sistemdeki tüm aday profillerini görüntüleyin, düzenleyin ve yönetin',
        'talent_bank_adv': 'Gelişmiş Yetenek Havuzu (Talent Pool)',
        'talent_bank_sub': 'Adayları yönetin, akıllı filtreleyin ve doğrudan iş fırsatlarına atayın',
        'import_excel': 'Excel\'den Aktar',
        'add_candidate': 'Yeni Aday Ekle',
        'kpi_total_talents': 'Havuzdaki Toplam Yetenek',
        'kpi_higher_edu': 'Yüksek Öğrenim Oranı (Y. Lisans/Doktora)',
        'kpi_avg_exp': 'Ortalama Aday Deneyimi',
        'years_exp': 'yıl',
        'search_candidate_placeholder': 'Ad, soyad, kimlik numarası veya e-posta ile ara...',
        'search_btn': 'Ara',
        'adv_filters_btn': '➕ Gelişmiş Eğitim, Deneyim & Yetenek Filtreleri',
        'degree_label': 'Eğitim Derecesi:',
        'degree_all': 'Tüm Dereceler',
        'degree_assoc': 'Ön Lisans',
        'degree_bach': 'Lisans',
        'degree_master': 'Yüksek Lisans',
        'degree_phd': 'Doktora',
        'major_label': 'Mezuniyet Bölümü:',
        'major_placeholder': 'Örn: Bilgisayar Mühendisliği',
        'skill_label': 'Yetenek/Beceri:',
        'skill_placeholder': 'Örn: Python',
        'min_exp_label': 'Min Deneyim (Yıl):',
        'min_exp_placeholder': 'Örn: 3',
        'min_exam_score_label': 'Min Yazılı Sınav Puanı:',
        'min_exam_placeholder': 'Örn: 75',
        'min_interview_score_label': 'Min Mülakat Puanı:',
        'min_interview_placeholder': 'Örn: 80',
        'min_assessment_score_label': 'Min Değerlendirme Merkezi Puanı:',
        'min_assessment_placeholder': 'Örn: 70',
        'applied_job_filter_label': 'Başvurulan İş Fırsatına Göre Filtrele:',
        'applied_job_placeholder': '-- İş Fırsatı Seçin --',
        'smart_recommendation_label': '🧠 İş İçin AI Uygunluk Önerileri:',
        'smart_recommendation_placeholder': '-- AI Eşleşme Analizi & Sıralaması İçin İş Seçin --',
        'clear_filters_btn': 'Filtreleri Temizle',
        'apply_adv_filters_btn': 'Gelişmiş Filtreleri Uygula',
        'cand_name_th': 'Aday Adı Soyadı',
        'cand_national_id_th': 'T.C. Kimlik / Sicil No',
        'cand_contact_th': 'İletişim Bilgileri',
        'cand_active_apps_th': 'Aktif Başvurular',
        'cand_personnel_lbl': 'Sicil No:',
        'cand_exam_lbl': 'Sınav:',
        'cand_interview_lbl': 'Mülakat:',
        'cand_assessment_lbl': 'Değerlendirme:',
        'cand_apps_count': 'başvuru',
        'cand_match_score': 'uyum',
        'assign_job_btn': '🔗 İşe Ata',
        'view_profile_btn': 'Profili Görüntüle',
        'cand_delete_confirm': 'Bu adayı ve tüm başvurularını silmek istediğinizden emin misiniz?',
        'cand_empty_list': 'Kriterlere uygun aday bulunamadı.',
        'showing_candidates': 'Toplam {total} adaydan {start} - {end} arası gösteriliyor',
        'modal_assign_title': 'Adayı Aktif İşe Ata',
        'modal_assign_text': '{name} adayını aktif bir işe atamak iş başvurusu oluşturacaktır.',
        'modal_assign_select_lbl': 'İş Fırsatı Seçin:',
        'modal_assign_select_placeholder': '-- Aktif İş Fırsatı Seçin --',
        'modal_assign_no_jobs': 'Sistemde aktif iş fırsatı bulunmamaktadır.',
        'modal_assign_submit': 'Atamayı Kaydet & Değerlendirmeyi Başlat',
        'modal_import_title': 'Excel\'den Toplu Aday İçe Aktarma',
        'modal_import_text': 'Bir Excel dosyası yükleyerek adayları toplu olarak içe aktarabilirsiniz. Veri formatının doğruluğu için lütfen önce örnek şablonu indirin.',
        'modal_import_download_template': 'Örnek Excel Şablonunu İndir',
        'modal_import_job_select_lbl': 'Atanacak İş Fırsatı (İsteğe Bağlı):',
        'modal_import_job_select_placeholder': '-- Genel Yetenek Havuzuna Kaydet (İş Ataması Olmadan) --',
        'modal_import_file_lbl': 'Excel Dosyası Seçin (.xlsx):',
        'modal_import_submit': 'Yükle & Adayları Kaydet',
        'stage_track_title': 'Değerlendirme Aşamalarına Göre Aday Takibi',
        'stage_track_sub': 'Değerlendirme aşamalarını izleme seçenekleriyle birlikte aktif süreçteki tüm adayların listesi',
        'stage_track_breadcrumbs': 'Aşamaya Göre Aday Takibi',
        'back_to_dashboard': 'Kontrol Paneline Dön',
        'export_excel_btn': 'Excel Çıktısı',
        'kpi_total_assessing': 'Toplam Değerlendirilen',
        'kpi_screening': 'Ön Eleme',
        'search_track_placeholder': 'Ad, kimlik no, iş kodu ile ara...',
        'filter_stage_placeholder': '-- Aşamaya Göre Filtrele --',
        'filter_job_placeholder': '-- İş Fırsatına Göre Filtrele --',
        'filter_dept_placeholder': '-- Departmana Göre Filtrele --',
        'apply_btn': 'Uygula',
        'table_th_stage': 'Mevcut Değerlendirme Aşaması',
        'table_th_score': 'Toplam Puan',
        'table_th_last_activity': 'Son Aktivite',
        'start_process': 'Süreci Başlat',
        'empty_track_list': 'Filtreyle eşleşen değerlendirmede aday bulunamadı.',
        'showing_track_candidates': 'Değerlendirmedeki toplam {total} adaydan {start} - {end} arası gösteriliyor',
        'planning_title': 'İşe Alım Planlaması & Kapasite Göstergeleri',
        'planning_sub': 'İşe alım takvimini yönetin, aşama SLA uyumluluğunu kontrol edin ve aylık değerlendirici kapasitesini izleyin',
        'planning_gantt_conflict': '🔍 Eşzamanlılık & Çakışmaları İzle',
        'planning_calendar_btn': '📅 İşe Alım Planlama Takvimi',
        'planning_excel_btn': '📥 Planları Excel\'e Aktar',
        'planning_config_btn': '⚙️ SLA & Kapasite Ayarları',
        'kpi_active_plans': 'Aktif Planlar',
        'kpi_delayed_plans': 'SLA Dışı (Geciken)',
        'kpi_draft_plans': 'Taslak Planlar',
        'kpi_today_jalali': 'Bugünün Tarihi (Şemsi)',
        'planning_active_badge': 'AKTİF',
        'planning_delayed_badge': 'GECİKEN',
        'planning_draft_badge': 'TASLAK',
        'planning_today_badge': 'BUGÜN',
        'planning_job_unit': 'iş fırsatı',
        'planning_plan_unit': 'plan',
        'planning_capacity_monthly': 'Aylık Değerlendirme Aşaması Kapasitesi ({month})',
        'planning_prev_month': '◀ Önceki Ay',
        'planning_next_month': 'Sonraki Ay ▶',
        'planning_candidate_limit': '{consumed} / {limit} aday',
        'planning_remaining_capacity': 'Kalan Kapasite: <strong>{remaining} kişi</strong>',
        'planning_consumed_percentage': '%{percentage} tüketildi',
        'planning_agenda_title': '📅 Gelecek 7 Günlük Gündem',
        'planning_agenda_sub': 'Gelecek hafta planlanan değerlendirme aşamalarının başlangıç ve bitiş tarihleri',
        'planning_agenda_excel': '📥 Haftalık Gündemi İndir',
        'planning_agenda_print': '🖨 Haftalık Gündem Yazdır / PDF',
        'planning_agenda_start': 'BAŞLANGIÇ',
        'planning_agenda_end': 'BİTİŞ',
        'planning_agenda_stage_text': '<strong class="text-dark">{job}</strong> işi için <strong class="text-dark">{stage}</strong> aşaması',
        'planning_no_agenda': 'Gelecek 7 gün için planlanmış etkinlik bulunmuyor.',
        'planning_unplanned_jobs_title': 'Planlanmamış İşler',
        'planning_unplanned_jobs_sub': 'Henüz bir iş planı kaydedilmemiş aktif iş fırsatları.',
        'planning_unplanned_code_headcount': 'Kod: {code} | Hedef kontenjan: {headcount}',
        'planning_unplanned_btn': '📅 İş Programını Planla',
        'planning_all_planned_msg': 'Tüm aktif iş fırsatları planlanmıştır.',
        'planning_active_plans_title': 'Aktif İşe Alım Planları & Görsel Zaman Tüneli',
        'planning_filter_active_badge': 'Aktif Filtre',
        'planning_search_placeholder': 'İş unvanı veya kod ara...',
        'planning_all_depts_placeholder': 'Tüm Departmanlar / Birimler',
        'planning_sort_newest': 'Önce En Yeni Planlar',
        'planning_sort_oldest': 'Önce En Eski Planlar',
        'planning_sort_start_asc': 'Başlangıç Tarihi (Eskiden Yeniye)',
        'planning_sort_start_desc': 'Başlangıç Tarihi (Yeniden Eskiye)',
        'planning_sort_end_asc': 'Tahmini Bitiş Tarihi (Artan)',
        'planning_sort_end_desc': 'Tahmini Bitiş Tarihi (Azalan)',
        'planning_sort_title': 'İş Unvanı (Alfabetik)',
        'planning_sort_headcount': 'Hedef Kontenjan (En Yüksek)',
        'planning_filter_submit': 'Filtreyi Uygula',
        'planning_headcount_lbl': 'Hedef Kontenjan: <strong class="text-primary">{count} kişi</strong>',
        'planning_start_lbl': 'Başlangıç: <strong>{date}</strong>',
        'planning_end_lbl': 'Tahmini Bitiş: <strong class="text-success">{date}</strong>',
        'planning_edit_btn': '📝 Planı Düzenle',
        'planning_pipeline_btn': '📊 Değerlendirme Aşamalarına Git',
        'planning_empty_plans_msg': 'Sistemde kayıtlı aktif işe alım planı bulunamadı.',
        'planning_empty_plans_sub': 'Sağ üstteki tablodan iş programı planlayın.',

        # --- Phase 3 Additions ---
        'cd_title': 'Aday Profili:',
        'cd_back': 'Aday Listesine Dön',
        'cd_sub': 'Kimlik bilgileri, eğitim, iş geçmişi ve değerlendirme geçmişinin tam gösterimi',
        'cd_new_app': 'Yeni Talep Kaydet (İşe Ata)',
        'cd_print_resume': 'Özgeçmiş Yazdır',
        'cd_edit_candidate': 'Adayı Düzenle',
        'cd_national_id': 'Kimlik No:',
        'cd_personnel_number': 'Sicil No:',
        'cd_phone': 'Telefon Numarası',
        'cd_email': 'E-posta Adresi',
        'cd_created_at': 'Sisteme Kayıt Tarihi',
        'cd_download_resume': 'Özgeçmiş Dosyasını İndir',
        'cd_no_resume': 'Yüklenmiş özgeçmiş dosyası yok',
        'cd_edu_title': 'Eğitim Geçmişi',
        'cd_graduation': 'Mezuniyet:',
        'cd_gpa': 'GPA / Not:',
        'cd_no_edu': 'Kayıtlı eğitim geçmişi bulunmuyor.',
        'cd_exp_title': 'İş Deneyimi',
        'cd_exp_range': 'Dönem:',
        'cd_now': 'Şimdiki Zaman',
        'cd_no_exp': 'Kayıtlı iş deneyimi bulunmuyor.',
        'cd_skills_title': 'Beceriler ve Diller',
        'cd_skills_sub': 'Uzmanlık Becerileri',
        'cd_no_skill': 'Kayıtlı beceri bulunmuyor.',
        'cd_langs_sub': 'Yabancı Diller',
        'cd_no_lang': 'Kayıtlı yabancı dil bulunmuyor.',
        'cd_certs_title': 'Sertifikalar ve Kurslar',
        'cd_certs_date': 'Alınma Tarihi:',
        'cd_certs_exp': 'Son Kullanma:',
        'cd_certs_no_exp': 'Son Kullanma Tarihi Yok',
        'cd_no_certs': 'Kayıtlı sertifika bulunmuyor.',
        'cd_apps_title': 'İş Başvuru Geçmişi',
        'cd_apps_job': 'İş Fırsatı',
        'cd_apps_date': 'Başvuru Tarihi',
        'cd_apps_stage': 'Mevcut Değerlendirme Aşaması',
        'cd_apps_score': 'Toplam Puan',
        'cd_apps_status': 'Genel Durum',
        'cd_apps_transcript': 'Değerlendirme Karnesi',
        'cd_no_apps': 'Bu aday için henüz iş başvurusu yapılmamıştır.',

        'cf_edit_title': 'Adayı Düzenle:',
        'cf_add_title': 'Yeni Aday Ekle',
        'cf_edit_sub': 'Aday Dosyasını Düzenle:',
        'cf_add_sub': 'Yeni Aday Kaydet',
        'cf_desc': 'Adayın kimlik, eğitim ve iş deneyimi bilgilerini girin',
        'cf_errors': 'Lütfen formdaki hataları kontrol edin ve düzeltin.',
        'cf_section_general': '1. Genel & Kimlik Bilgileri',
        'cf_first_name': 'Ad',
        'cf_last_name': 'Soyad',
        'cf_national_id': 'T.C. Kimlik No',
        'cf_personnel': 'Sicil Numarası (kurum içi personeller için)',
        'cf_phone': 'Telefon Numarası',
        'cf_email': 'E-posta Adresi',
        'cf_resume': 'Özgeçmiş Dosyası (PDF veya Word)',
        'cf_current_file': 'Mevcut Dosya:',
        'cf_view_resume': 'Mevcut Özgeçmişi Görüntüle',
        'cf_section_edu': '2. Eğitim Geçmişi',
        'cf_add_edu': 'Eğitim Geçmişi Ekle',
        'cf_degree': 'Eğitim Derecesi',
        'cf_major': 'Mezuniyet Bölümü',
        'cf_univ': 'Üniversite / Kurum',
        'cf_gpa': 'Not Ortalaması',
        'cf_grad_year': 'Mezuniyet Yılı',
        'cf_delete_row': 'Kaydı Sil',
        'cf_section_exp': '3. İş Deneyimi',
        'cf_add_exp': 'İş Deneyimi Ekle',
        'cf_company': 'Şirket / Kurum Adı',
        'cf_job_title': 'İş Unvanı',
        'cf_start_date': 'Başlangıç Tarihi (Şemsi)',
        'cf_end_date': 'Bitiş Tarihi (Şemsi)',
        'cf_exp_desc': 'Açıklama & Başarılar',
        'cf_save': 'Değişiklikleri Kaydet',
        'cf_create': 'Adayı Kaydet',

        'jf_edit_title': 'İş Fırsatını Düzenle',
        'jf_add_title': 'Yeni İş Fırsatı Ekle',
        'jf_edit_sub': 'İş Fırsatını Düzenle:',
        'jf_desc': 'İş fırsatı ayrıntılarını ve aday değerlendirme aşamalarını yapılandırın',
        'jf_section_general': '1. Genel İş Bilgileri',
        'jf_req_num': 'Talep Numarası',
        'jf_code': 'İş Kodu',
        'jf_title': 'İş Unvanı',
        'jf_dept': 'Departman',
        'jf_unit': 'Organizasyonel Birim',
        'jf_cat': 'Görev Seviyesi/Kategorisi',
        'jf_headcount': 'Hedef Kontenjan',
        'jf_type': 'İstihdam Türü',
        'jf_section_planning': '2. Planlama & Takvim',
        'jf_recruiter': 'Atanan İşe Alım Uzmanı',
        'jf_workflow': 'İş Akışı Şablonu (Workflow)',
        'jf_workflow_help': 'Şablon seçildiğinde değerlendirme aşamaları otomatik doldurulur.',
        'jf_status': 'İş Fırsatı Durumu',
        'jf_start_date': 'Başlangıç Tarihi',
        'jf_end_date': 'Bitiş Tarihi',
        'jf_section_competencies': '3. Değerlendirilecek Yetkinlikler',
        'jf_competencies_help': 'Bu iş için gerekli olan ana yetkinlikleri seçin. Bunlar değerlendirme merkezindeki değerlendirmelerin temelini oluşturacaktır.',
        'jf_section_stages': '4. Değerlendirme Aşamalarını & Ağırlıklarını Yönet',
        'jf_stages_help': 'Adayları değerlendirmek için aşamaları ve ağırlıkları belirtin. Ağırlıkların toplamı tam olarak %100 olmalıdır.',
        'jf_stage_name': 'Aşama Adı',
        'jf_stage_type': 'Değerlendirme Türü',
        'jf_stage_weight': 'Ağırlık (٪)',
        'jf_stage_pass': 'Minimum Geçiş Puanı (100 üzerinden)',
        'jf_stage_seq': 'Sıralama',
        'jf_add_stage': '➕ Yeni Aşama Ekle',
        'jf_total_weight': 'Toplam Ağırlık:',
        'jf_weight_error': 'Uyarı: Ağırlıkların toplamı tam olarak %100 olmalıdır.',

        'jp_title': 'Değerlendirme Aşamaları:',
        'jp_back': 'İş Fırsatlarına Dön',
        'jp_sub': 'Aday değerlendirme aşamaları:',
        'jp_code': 'İş Kodu:',
        'jp_dept': 'Departman:',
        'jp_unit': 'Organizasyonel Birim:',
        'jp_cat': 'Görev Seviyesi:',
        'jp_print': 'Yazdır & Doküman Çıktıları',
        'jp_doc_exam': 'Yazılı Sınav Belgesi',
        'jp_doc_ad': 'İş İlanı Belgesi',
        'jp_doc_ap': 'Assessment Plan Belgesi',
        'jp_doc_spec': 'Sınav Merkezi Özellikleri',
        'jp_final_ranking': '🏆 Nihai Aday Sıralaması',
        'jp_total_candidates': 'Toplam Kayıtlı Aday:',
        'jp_stages_title': 'Değerlendirme Aşamaları & Ağırlıkları',
        'jp_stage_completed': 'Değerlendirme Tamamlandı',
        'jp_stage_weight': 'Aşama Ağırlığı:',
        'jp_all_completed_title': 'Tüm aşamaların değerlendirmesi tamamlandı!',
        'jp_all_completed_desc': 'Tanımlanan tüm aşamalardaki tüm aktif adaylar değerlendirildi. Artık nihai sıralamaları görebilir ve karar verebilirsiniz.',
        'jp_all_completed_btn': '🏆 Nihai Sıralamaları Gör & Karar Ver',

        'se_title': 'Hızlı Puan ve Değerlendirme Girişi',
        'se_desc': 'İş fırsatını seçin ve mevcut aşamadaki değerlendirme puanlarını ve durumlarını doğrudan kaydedin.',
        'se_search_job': '🔍 İş Ara (Kod veya Unvana Göre)',
        'se_search_placeholder': 'Örn: Mühendis, Denetçi, 4120...',
        'se_search_btn': 'Ara',
        'se_search_found': 'eşleşen iş fırsatları bulundu',
        'se_select_job': 'İş Fırsatı Seçin',
        'se_select_placeholder': '-- Puan girişi yapmak için lütfen bir iş fırsatı seçin --',
        'se_loading': 'Değerlendirme matrisi yükleniyor...',
        'se_closed_warning': '⚠️ Uyarı: Bu iş fırsatı şu anda "{status}" durumunda Kapatılmış/İptal edilmiştir. Değişiklik yapılamaz.',
        'se_success': 'Değerlendirme puanları ve durumları başarıyla kaydedildi.',
        'se_path': '🗺️ İşe Alım Süreç Yolu:',
        'se_search_cand': 'Aday ara (Ad, Soyad veya Kimlik Numarasına göre):',
        'se_search_cand_placeholder': 'Aramak için yazmaya başlayın...',
        'se_filter': 'Adayları filtrele:',
        'se_filter_pending': 'Sadece inceleme altındaki adaylar (IN_PROGRESS)',
        'se_filter_completed': 'Sadece kesinleşmiş kararlar (Tamamlandı)',
        'se_filter_all': 'Bu işe başvuran tüm adaylar',
        'se_show_failed': 'Elenen / reddedilen adayları göster',
        'se_bypass': 'Serbest puan girişi (Sıralama kilitlerini baypas et)',
        'se_status_locked': '🔒 Kilitli (Önceki aşamada elendi)',
        'se_no_stage': 'Aktif aşama yok',
        'se_score_lbl': 'Puan:',
        'se_status_lbl': 'Durum:',
        'se_date_lbl': 'Değerlendirme Tarihi:',
        'se_evaluator_lbl': 'Atanan Değerlendirici:',
        'se_pass': 'GEÇTİ',
        'se_fail': 'ELENDİ',
        'se_no_show': 'KATILMADI',
        'se_ac_details': '🎯 Değerlendirme Merkezi Puan Tablosu',
        'se_int_details': '💬 Mülakat Puan Paneli',
        'se_save_all': '💾 Tüm Puanları Kaydet ve Gönder',
        'se_no_cands': 'Seçilen filtrelere uygun aday bulunamadı.',
        'se_no_evaluations': 'Bu iş için tanımlanmış değerlendirme aşaması bulunmuyor.',

        'fr_title': 'Nihai Aday Sıralaması & Seçim Kararları',
        'fr_sub': 'Hedef İş Fırsatı:',
        'fr_back': 'Değerlendirme Aşamalarına Dön',
        'fr_excel': 'Sıralamayı Excel\'e Aktar',
        'fr_total_candidates': 'Toplam Aday',
        'fr_headcount': 'Hedef Kontenjan',
        'fr_average_score': 'Ortalama Toplam Puan',
        'fr_assessing_count': 'Nihai Karar Bekleyenler',
        'fr_rank': 'Sıra',
        'fr_weighted_score': 'Ağırlıklı Toplam Puan',
        'fr_stages_breakdown': 'Değerlendirme Aşaması Puanları',
        'fr_final_decision': 'Nihai Seçim Kararı',
        'fr_select_status': '-- Nihai Kararı Seçin --',
        'fr_status_inprogress': 'Nihai İnceleme Altında',
        'fr_status_selected': 'Seçildi (Kabul Edildi)',
        'fr_status_reserve': 'Yedek Listesi',
        'fr_status_rejected': 'Elendi',
        'fr_save_decisions': '💾 Tüm Adaylar İçin Seçim Kararlarını Kaydet ve Kesinleştir',
    }
}

class TranslationDict(dict):
    """
    دیکشنری سفارشی ترجمه با قابلیت فال‌بک هوشمند.
    در صورتی که کلیدی در زبان جاری یافت نشود، از زبان فارسی استفاده می‌کند.
    اگر در فارسی هم نباشد، عنوان کلید را به صورت متن قابل خواندن باز می‌گرداند تا منوها هرگز خالی نمانند.
    """
    def __init__(self, primary_dict, fallback_dict=None):
        super().__init__(primary_dict or {})
        self.fallback_dict = fallback_dict or {}

    def __getitem__(self, key):
        if key in self:
            return super().__getitem__(key)
        if self.fallback_dict and key in self.fallback_dict:
            return self.fallback_dict[key]
        return str(key).replace('_', ' ').title()

    def get(self, key, default=None):
        if key in self:
            return super().__getitem__(key)
        if self.fallback_dict and key in self.fallback_dict:
            return self.fallback_dict[key]
        return default if default is not None else str(key).replace('_', ' ').title()


def translation_processor(request):
    lang_code = getattr(request, 'LANGUAGE_CODE', 'fa')
    base_lang = lang_code.split('-')[0].lower() if lang_code else 'fa'
    
    primary = dict(TRANSLATIONS.get(base_lang, TRANSLATIONS.get('fa', {})))
    fallback = TRANSLATIONS.get('fa', {})

    organization_name = 'سیستم جذب'
    org_setting = None
    try:
        from django.db import DatabaseError
        from apps.jobs.models import OrganizationSetting

        org_setting = OrganizationSetting.objects.filter(is_deleted=False).first()
        if org_setting and org_setting.name:
            organization_name = org_setting.name
    except DatabaseError:
        # Keep templates renderable during initial setup and migrations.
        pass

    primary['system_title'] = organization_name
    primary['sidebar_title'] = organization_name
    
    return {
        't': TranslationDict(primary, fallback if base_lang != 'fa' else None),
        'current_language_code': base_lang,
        'organization_name': organization_name,
        'org_setting': org_setting,
    }
